### ISSUE TITLE
Invoke blt frontend from inside drupalVM

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1009]
When DrupalVM is configured for a BLT repo, and a user executes  `blt frontend`  from outside the VM  please ssh into the vm and  execute `blt frontend` from inside the VM.  This will ensure consistent experience for front-end build tools, and remove local install problems.

**Comment by geerlingguy** [comment]
Most Windows devs seem to do this, and it makes the consistency of local builds a little better, as you can guarantee all devs will have the exact same Node.js version installed, and gulp can be installed globally in the VM.

For one project where we have a mix of Mac and Windows-based developers, we added the following configuration to power asset compilation for Sass/KSS for Cog (also works with Bootstrap):

```yaml
nodejs_version: "4.x"
nodejs_npm_global_packages:
  - name: gulp
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"
installed_extras:
  ...
  - nodejs
  ...
```

Otherwise, each developer has to manually install Node.js... or `nvm`, or `avn`, or run the `install_node.sh` script in the Cog theme directory, and also make sure to install `yarn` and `gulp`, and it can start getting a little dizzying having to install multiple node versions, multiple package managers, and other software—not to mention getting the right version (if you have version mismatches, and build the theme with Node 4.x, then again with 6.x, you'll likely run into funny errors with `node-sass` and have to delete your `node_modules` folder entirely).
