### ISSUE TITLE
Missing space in .travis.yml causes travis-ci validation error.

### ISSUE THREAD

**Issue by mariagwyn** [acquia/blt#1090]
My system information:
* BLT version: 8.6.12

Did the following:
* Updated to 8.6.12.
* remove and initialized new .travis.yml.

When travis-ci is run this error results:
```
ERROR: An error occured while trying to parse your .travis.yml file.
Please make sure that the file is valid YAML.
http://lint.travis-ci.org can check your .travis.yml.
The log message was: Build config file had a parse error: did not find expected key while parsing a block mapping at line 2 column 1.
```

After validating by removing lines, apparently there is a missing space at line 59, the SECOND `- provider:`:
```
deploy:
   - provider: script
     script: source $BLT_DIR/scripts/travis/deploy_branch
     skip_cleanup: true
     on:
       branch: develop
       php: 5.6
  - provider: script
     script: source $BLT_DIR/scripts/travis/deploy_branch
     skip_cleanup: true
     on:
       branch: master
       php: 5.6
   - provider: script
     script: source $BLT_DIR/scripts/travis/deploy_tag
     skip_cleanup: true
     on:
       tags: true
       php: 5.6
```

After removing the space, travis continues on as it should.
