### ISSUE TITLE
Multiple git remotes?

### ISSUE THREAD

**Issue by kevinquillen** [acquia/blt#1320]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.1
* BLT version: 8.6.15

In the `project.yml` file, is there a way to define multiple git remotes?

```
git:
  default_branch: develop
  remotes:
    - user@url:project.git
```

## Scenario

I have multiple remotes on different servers. For demonstration / develop purposes, the development server is living on a free Acquia account. The staging and production servers are _not_ on Acquia, but I need to build and deploy all the same.

Is there a way to do this currently? I checked the docs but could not locate information. The build/deploy command works for develop, I would like a similar process for staging and production as well.

Should I just set up Jenkins to handle this?

**Comment by grasmash** [comment]
You can just add another remote to the git.remotes array:
```
git:
  default_branch: develop
  remotes:
    - user@url:project.git
    - user@url2:project.git
```
