### ISSUE TITLE
Travis CI: MySQL is not available

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#1509]
My system information:
* Operating system type: Travis CI
* BLT version: 8.x.dev (8.9.x)

When I run this command:
```
blt setup:drupal:install
```

I get the following output:
```
MySQL is not available
```

And I expected this to happen:

Drupal installation

Note that this was fixed by swapping out the default alias in project.yml.

```
drush:
  aliases:
    remote: <project>.test
    local:<project>.local
    ci: self
    default_alias: '${drush.aliases.local}'
  default_alias: self
```
