### ISSUE TITLE
Refactor command names to match configuration hierarchy

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#1524]
With 8.9.x, we have to opportunity to do some refactoring of the command names and configuration structure. Tentative plan is below.

default config:

```
blt:
  bin.path: vendor/bin
  command-cache-dir: ${blt.root}/cache/commands
  config-files:
    project: ${repo.root}/blt/project.yml
    local: ${repo.root}/blt/project.local.yml
    example-local: ${repo.root}/blt/example.project.local.yml
    schema-version: ${repo.root}/blt/.schema_version
    multisite: ${docroot}/sites/${multisite.name}/site.yml
  update:
    ignore-existing-file: ${blt.root}/scripts/blt/ignore-existing.txt

composer:
  bin: ${repo.root}/${bin.path}
  extra: ''

cm:
  strategy: config-split
  core:
    path: ../config
    key: sync
    deploy-key: vcs
    dirs:
      sync:
        path: ${cm.core.path}/default
  features:
    no-overrides: true

deploy:
  command: ~
  build-dependencies: true
  dir: ${repo.root}/deploy
  exclude_file: ${blt.root}/scripts/blt/deploy/deploy-exclude.txt
  exclude_additions_file: ${repo.root}/blt/deploy-exclude-additions.txt
  git:
    ignore-file: ${blt.root}/scripts/blt/deploy/.gitignore
    failOnDirty: true

docroot: ${repo.root}/docroot

drupal:
  account.mail: no-reply@acquia.com
  locale: en
  local_settings_file: ${docroot}/sites/default/settings/local.settings.php
  settings_file: ${docroot}/sites/default/settings.php

drush:
  bin: ${composer.bin}/drush
  dir: ${docroot}
  uri: default
  assume: yes
  sanitize: true

git:
  hooks:
    pre-commit: ${blt.root}/scripts/git-hooks
    commit-msg: ${blt.root}/scripts/git-hooks

# You may provide a list of sites for BLT to run commands against,
# otherwise BLT will generate this sites list based on directories
# in ${docroot}/sites/*/
#
# multisites
#   - default

fix:
  command:
    phpcbf: true
  phpcbf:
    filesets:
      - files.php.custom.modules
      - files.php.tests
      - files.php.custom.themes
      - files.frontend.custom.themes

project:
  local:
    uri: ${project.local.protocol}://${project.local.hostname}

setup:
  command:
    install-drupal: true
    sync: true
    import-config: true
    execute-updates: true
  sync:
    db: true
    files: false

tests:
  behat:
    config: ${repo.root}/tests/behat/local.yml
    strict: true
    profile: local
    run-server: false
    server-url: http://127.0.0.1:8888
    web-driver: phantomjs
    paths:
      # - ${docroot}/modules
      # - ${docroot}/profiles
      - ${repo.root}/tests/behat
    tags: '~ajax&&~experimental&&~lightningextension'
    extra: ''
  command:
    behat: true
    phpunit:true
    security-updates: true
  phpunit:
    - path: '${repo.root}/tests/phpunit'
      config: null
  reports:
    localDir: ${repo.root}/reports
    remoteDir: reports

validate:
  command:
    lint: true
    phpcs: true
    twig: true
    yaml: true
  lint:
    filesets:
      - files.php.custom.modules
      - files.php.custom.themes
      - files.php.tests
  phpcs:
    filesets:
      - files.php.custom.modules
      - files.php.tests
      - files.php.custom.themes
      - files.frontend.custom.themes
  twig:
    filesets:
      - files.twig
  yaml:
    filesets:
      - files.yaml
```

Commands:
```
setup
setup:install:drupal   sid
setup:sync             ss
setup:sync:db          ssd
setup:sync:files       ssf
setup:import-config    sic
setup:execute-updates  seu

validate
validate:lint
validate:phpcs
validate:twig
validate:yaml
```

This will allow the `setup` command behavior to be configurable, and will allow us to remove some commands...

The `local:*` and `ci:*` commands are all being removed!
