### ISSUE TITLE
`post-config-import` doesn't expand ${environment} on `setup:update`

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#1531]
Running BLT version 8.8.3 with #1522, when I run `blt local:refresh`, my `post-config-import` command properly expands `${environment}`. But when I run `blt setup:update`, it does not. So here are the relevant lines from my `project.yml`:

```yaml
  post-config-import:
    dir: '${docroot}'
    command: '../scripts/custom/migrations.sh ${environment}'
```

And here's what actually gets run:

| Command | Executed |
|---------------------|-----------------------------------------|
| `blt local:refresh` | `../scripts/custom/migrations.sh local` |
| `blt setup:update` | `../scripts/custom/migrations.sh ` |

I'm afraid I don't have time to look into this myself right now, so I'm just throwing the report over the wall. Thanks!
