### ISSUE TITLE
Split up "run-tests"

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1541]
Currently the pipelines log reads like a firehose.  Its a LOT.    Thinking that it could be made much more navigable if we break the run-tests task [here (https://github.com/acquia/blt/blob/8.x/scripts/pipelines/acquia-pipelines.yml#L26)  into 2-3 targets 
```
        - run-tests:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/run_tests
```

like:
- prep
- code linting
- automated testing

That way you have clickable expandable regions that get you to the information you need as opposed to a single column of text!
