### ISSUE TITLE
BLT Fails to run config-import sync on cloudhooks

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1675]
BLT Fails to run config-import sync on Normal envs AND ODE when invoked via cloud hooks:
```
. /var/www/html/$site.$target_env/vendor/acquia/blt/scripts/cloud-hooks/functions.sh
  deploy_updates

```
Also when this happens, drush cex sync fails but the cloud hook doesn't error out.

```
mysite@mysite:/var/www/html/mysite.ode59/docroot$ ../vendor/bin/blt deploy:update
Deploying updates to mysite.com...
> setup:config-import
Executing pre-config-import target hook...
[ExecStack] echo 'No pre-config-import configured.'
No pre-config-import configured.
[Acquia\Blt\Robo\Tasks\DrushTask] Running /mnt/www/html/mysiteode59/vendor/bin/drush cc drush --uri=default --yes in /mnt/www/html/mysiteode59/docroot
'drush' cache was cleared.                                                                                                                          [success]
[Acquia\Blt\Robo\Tasks\DrushTask] Done in 0.715s
[Acquia\Blt\Robo\Tasks\DrushTask] Running /mnt/www/html/mysiteode59/vendor/bin/drush cache-rebuild --uri=default --yes in /mnt/www/html/mysiteode59/docroot
Cache rebuild complete.                                                                                                                             [ok]
[Acquia\Blt\Robo\Tasks\DrushTask] Done in 5.646s
[Acquia\Blt\Robo\Tasks\DrushTask] Running /mnt/www/html/mysiteode59/vendor/bin/drush updb --uri=default --yes in /mnt/www/html/mysiteode59/docroot
No database updates required                                                                                                                        [success]
[Acquia\Blt\Robo\Tasks\DrushTask] Done in 6.846s
[Acquia\Blt\Robo\Tasks\DrushTask] Running /mnt/www/html/mysiteode59/vendor/bin/drush cache-rebuild --uri=default --yes in /mnt/www/html/mysiteode59/docroot
Cache rebuild complete.                                                                                                                             [ok]
[Acquia\Blt\Robo\Tasks\DrushTask] Done in 11.76s
Checking for features overrides...
Checking for config overrides...
[Acquia\Blt\Robo\Tasks\DrushTask] Running /mnt/www/html/mysiteode59/vendor/bin/drush cex sync --uri=default --no in /mnt/www/html/mysiteode59/docroot
Differences of the active config to the export directory:

 Collection  Config                              Operation
             purge.logger_channels               create
             acquia_connector.settings           create
             purge.plugins                       create
             purge_queuer_coretags.settings      create
             core.extension                      update
             block.block.vuejsintegrationblock.  delete
             block.block.footerlegal             delete
             system.menu.footer-legal            delete
             block.block.footer                  delete
The .yml files in your export directory (/mnt/www/html/mysiteode59/config/mysite.com) will be deleted and replaced with the active config. (y/n): n
Cancelled.                                                                                                                                          [cancel]
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 75  Time 1.498s
[error]  Configuration in the database does not match configuration on disk. You must re-export configuration to capture the changes. This could also indicate a problem with the import process, such as changed field storage for a field with existing content. To permit configuration overrides, set cm.allow-overrides to true in blt/project.yml.
> setup:toggle-modules
Finished deploying updates to mysite.com.

```

Note this works fine locally

**Comment by aweingarten** [comment]
I think the issue is here
https://github.com/acquia/blt/blob/8.x/src/Robo/Commands/Setup/ConfigCommand.php#L110

**Comment by aweingarten** [comment]
So that worked!  It seems like VCS might no longer be a thing on ACE?

**Comment by grasmash** [comment]
I think this has to do with the fact that you're using multisite and you are not using the `default` directory. 

These are the default config paths for BLT cm:
```
cm:
    dirs:
      # Corresponding value is defined in config.settings.php.
      sync:
        path: ${cm.core.path}/default
      vcs:
        path: ${cm.core.path}/default
```

If you are, for instance, using `${cm.core.path}/mysite.com` rather than `${cm.core.path}/default`, you'll need to set the following values:

```
cm:
    dirs:
      # Corresponding value is defined in config.settings.php.
      sync:
        path: ${cm.core.path}/mysite.com
      vcs:
        path: ${cm.core.path}/mysite.com
```

It might help if BLT changed the default config to:
```
cm:
    dirs:
      # Corresponding value is defined in config.settings.php.
      sync:
        path: ${cm.core.path}/default
      vcs:
        path: ${cm.dirs.sync.path}
```
