### ISSUE TITLE
Document using Behat with Drupal VM

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#176]
Draft docs
------------------------

# Drupal VM and Behat tests

## Using the Drupal Extension's "drupal" driver with Drupal VM

The Drupal Extension for Behat has an inherent limitation: it cannot use the 'drupal' driver to bootstrap Drupal on a remote server. If you're using Drupal VM and would like to execute Behat tests using the 'drupal' driver, you must execute them from within the VM. This is a break of the established pattern of running all BLT commands outside of the VM.

To execute Behat tests using the 'drupal' driver on a Drupal VM environment, you must do the following:

1. Update `tests/behat/local.yml` with the absolute file path to your project _inside the VM_. I.e., find and replace all instances of `host/machine/path/to/repo` with `/vm/path/to/repo`, which should look something like `var/www/[project.machine_name]`. 
1. SSH into the VM `vagrant ssh`.
1. Change to your project directory `cd /var/www/[project.machine_name]`.
1. Assert that PhantomJS is installed for VM: `composer run-script install-phantomjs`
1. Execute behat tests `./blt.sh tests:behat`

## Using the Drupal Extension's "drush" driver with Drupal VM

You may choose to write only behat tests that utilize the Drupal Extension's "drupal" driver.

**Comment by justinlevi** [comment]
I think there is an issue running @javascript behat tests on Drupal-vm as well right? The example feature throws the error below when running from within the stock Drupal-vm

```
@javascript
Feature: Selenium Test
  In order to test if Selenium is working
  As a user
  I need to be able to load the homepage

  Scenario: Load a page
    Given I am on "/"
    Then I should see the text "Log in"
```

```
vagrant@data:/var/www/data$ ./vendor/bin/behat tests/behat/features/Examples.feature --config=tests/behat/l ocal.yml -p local
@javascript
Feature: Selenium Test
  In order to test if Selenium is working
  As a user
  I need to be able to load the homepage

  Scenario: Load a page                 # features/Examples.feature:7
    Given I am on "/"                   # Drupal\DrupalExtension\Context\MinkContext::visit()
      Could not open connection: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html (Behat\Mink\Exception\DriverException)
    Then I should see the text "Log in" # Drupal\DrupalExtension\Context\MinkContext::assertTextVisible()

--- Failed scenarios:

    features/Examples.feature:7

1 scenario (1 failed)
2 steps (1 failed, 1 skipped)
0m10.20s (24.46Mb)
```

I don't believe the chrome-driver is installed by default so even if you have selenium is up and running it won't work as expected.

**Comment by justinlevi** [comment]
Update: this may have been an oversight on my part. Given the following `local.yml`, my @javascript tests seem to execute as expected after starting up my selenium server from within the VM

`sudo /etc/init.d/selenium start`

```
# To generate a local.yml file using this the example template, execute:
# `./blt.sh setup:behat` from the project root.
imports:
  - behat.yml

local:
  suites:
    default:
      paths:
        # Set features to repo root so that .feature files belonging to contrib
        # modules, themes, and profiles can be discovered. Enable these
        # additional paths in build/phing/build.yml.
        features: /var/www/data
        bootstrap: /var/www/data/tests/behat/features/bootstrap
      contexts:
        - Drupal\FeatureContext:
          parameters:
            environment:
              # absolute path to local directory to store screenshots - do not include trailing slash
              screenshot_dir: '/Users/username/Desktop/test'
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      javascript_session: selenium2
      # configure the base url for your site
      base_url: http://data.vm
      # set default command for "Show last response" step.
      show_cmd: "open %s"
      goutte:
        guzzle_parameters:
          redirect.disable: true
          ssl.certificate_authority: system
          curl.options:
            CURLOPT_SSL_VERIFYPEER: false
            CURLOPT_SSL_VERIFYHOST: false
            CURLOPT_CERTINFO: false
            CURLOPT_TIMEOUT: 120
      # ADDITIONAL OPTIONS FOR WEB DRIVERS
      # use the following 3 lines to use phantomjs
      browser_name: phantomjs
      selenium2:
        wd_host: "http://localhost:4444/wd/hub"
      #  browser: chrome


    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drush:
        alias: '@data.vm'
      drupal:
        # This must be an absolute path.
        drupal_root: /var/www/data/docroot
      drush:
        alias: '@data.vm'
        global_options: '--strict=0'
      region_map:
        header: "#header"
        content: "#content"
        footer: "#footer"
      selectors:
        message_selector: '.messages'
        error_message_selector: '.messages.messages-error'
        success_message_selector: '.messages.messages-status'

# example-multisite:
#   extensions:
#     Behat\MinkExtension:
#       javascript_session: selenium2
#       # Configure the base url for your site. For multisite, ensure that this
#       # corresponds to a valid domain entry in sites.php.
#       base_url: http://127.0.0.1:8889
#       # set default command for "Show last response" step.
#       show_cmd: "open %s"
#       selenium2:
#         wd_host: http://127.0.0.1:4444/wd/hub
#         browser: chrome
#     Drupal\DrupalExtension:
#       drupal:
#         # This must be an absolute path.
#         drupal_root: /var/www/data/docroot
#       drush:
#         alias: '@self'
```

**Comment by justinlevi** [comment]
Took me a minute to figure out how to run the `./blt.sh behat:tests:execute` command so thought I'd throw an example in here for that. 

`/blt.sh tests:behat:execute -D behat.path=$(pwd)/tests/behat/features`

Running this should try and execute all tests in the tests/behat/features directory.

**Comment by grasmash** [comment]
@justinlevi You shouldn't actually need selenium server at all. By default, the tests are run via PhantomJS, which "spoofs" a selenium server. Running `blt tests:behat` will start PhantomJS on the default port and then run all Behat tests in the `behat.paths` array, which is set to a default value here: https://github.com/acquia/blt/blob/8.x/template/build/core/phing/build.yml#L12. 

You can override the paths in `build/custom/phing/build.yml.`

**Comment by justinlevi** [comment]
@grasmash Thanks so much for the help! I'm still super new to behat testing so I'm sure I'm missing something obvious here. 

Given the default `local.yml` settings, I can't seem to get the `Example.feature` to run.

The following command on my host machine, where I don't have selenium running, gives me the following error: 

$ `./vendor/bin/behat -c tests/behat/local.yml tests/behat/features/Examples.feature`

Returns this error: 
```
 [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                  
  The javascript session must be one of the enabled javascript sessions ([]), but got selenium2  
```

Here's what my `local.yml` looks like:
```
# To generate a local.yml file using this the example template, execute:
# `./blt.sh setup:behat` from the project root.
imports:
  - behat.yml

local:
  suites:
    default:
      paths:
        # Set features to repo root so that .feature files belonging to contrib
        # modules, themes, and profiles can be discovered. Enable these
        # additional paths in build/phing/build.yml.
        features: /var/www/data
        bootstrap: /var/www/data/tests/behat/features/bootstrap
      contexts:
        - Drupal\FeatureContext:
          parameters:
            environment:
              # absolute path to local directory to store screenshots - do not include trailing slash
              screenshot_dir: '/var/www/data/tests'
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      javascript_session: selenium2
      # configure the base url for your site
      base_url: http://127.0.0.1:8080
      # set default command for "Show last response" step.
      show_cmd: "open %s"
      # ADDITIONAL OPTIONS FOR WEB DRIVERS
      # use the following 3 lines to user phantomjs
      browser_name: phantomjs
      selenium2:
         wd_host: "http://127.0.0.1:4444/wd/hub"
         browser: chrome
      # use the following lines to disable SSL authentication for goutte.
      goutte:
       guzzle_parameters:
        redirect.disable: true
        ssl.certificate_authority: system
        curl.options:
             CURLOPT_SSL_VERIFYPEER: false
             CURLOPT_SSL_VERIFYHOST: false
             CURLOPT_CERTINFO: false
             CURLOPT_TIMEOUT: 120
    Drupal\DrupalExtension:
      drupal:
        # This must be an absolute path.
        drupal_root: /Users/justinwinter/Sites/data/docroot
      drush:
        alias: '@self'
        global_options: '--strict=0'
```

The error exception doesn't mean much to me and I'm not really sure where I should be looking for more information on this. 

Should this Example.feature work out of the box?
