### ISSUE TITLE
Modifying BLT Configuration definition is not accurate

### ISSUE THREAD

**Issue by uenrico** [acquia/blt#2046]
My system information:
* Operating system type: Windows10 (host), DrupalVM (guest)
* Operating system version: Ubuntu 16.04.3 LTS
* BLT version: 8.9.2

BLT Configuration definition said "BLT configuration can be customized by overriding the value of default variable values... Values loaded from the later files will overwrite values in earlier files."

That definition is not accurate because when project.yml and project.local.yml are loaded an array_merge is executed (arrayMergeRecursiveDistinct) instead of a real array override.

**project.yml (partial)**
```
modules:
    local:
        enable: [dblog, devel, seckit, views_ui]
        uninstall: [acsf, acquia_connector, shield]
```

**project.local.yml (partial)**
```
modules:
    local:
        enable: [dblog, devel, seckit, views_ui]
        uninstall: {  }
```

I get the following output:

```
modules:
    local:
        enable: [dblog, devel, seckit, views_ui]
        uninstall: [acsf, acquia_connector, shield]
```

And I expected this to happen:
**modules.local.uninstall** should be empty if we are expecting an override,
