### ISSUE TITLE
PHP Warning when using modules.local.uninstall: null

### ISSUE THREAD

**Issue by uenrico** [acquia/blt#2048]
My system information:
* Operating system type: Windows10 (host), DrupalVM (guest)
* Operating system version: Ubuntu 16.04.3 LTS
* BLT version: 8.9.2

Note: issue related to [https://github.com/acquia/blt/issues/2046](url)

When using:

**project.local.yml** (partial)

```
modules:
    local:
        enable: [dblog, devel, seckit, views_ui]
        uninstall: null
```
and execute `BLT setup`

I get the following output:
```
PHP Warning: implode(): Invalid arguments passed in /vendor/acquia/blt/src/Robo/Commands/Setup/ToggleModulesCommand.php on line 70

Warning: implode(): Invalid arguments passed in /vendor/acquia/blt/src/Robo/Commands/Setup/ToggleModulesCommand.php on line 70
```
