### ISSUE TITLE
Acquia Search Patch Issues

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#2246]
My system information:
* Operating system type: Ubuntu (Drupal VM)
* Operating system version: 1604
* BLT version: 8.9.10

I patched my local following the guidelines on: https://github.com/acquia/blt/commit/4f146f756c8b1dd1cdef8f3980f199925d784f58#diff-94b89e532e79ac5a410d76450f90dea8

When I tried to get SOLR to run, I got nothing but bad news (see below). Rebuilding the VM using @geerlingguy's default script in examples/scripts/configure-solr.sh inside of the Drupal-VM vendor package worked fine. 

I get the following output:
```
$ sudo service solr status
* solr.service - Apache SOLR
   Loaded: loaded (/etc/systemd/system/solr.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2017-11-02 21:26:47 UTC; 6min ago
  Process: 1086 ExecStop=/bin/kill -s QUIT $MAINPID (code=exited, status=0/SUCCESS)
  Process: 1065 ExecStart=/opt/solr/bin/solr -e cloud -noprompt (code=exited, status=203/EXEC)
 Main PID: 1065 (code=exited, status=203/EXEC)
Nov 02 21:26:47 local systemd[1]: Started Apache SOLR.
Nov 02 21:26:47 local systemd[1]: solr.service: Main process exited, code=exited, status=203/EXEC
Nov 02 21:26:47 local systemd[1]: solr.service: Unit entered failed state.
Nov 02 21:26:47 local systemd[1]: solr.service: Failed with result 'exit-code'.
```

Nothing was written to the SOLR logs. We tried several methods of starting solr, and it failed every time.

here is the box/config.yml file (from before I nuked and rebuilt with the example from Drupal VM).

```
# Update the hostname to the local development environment hostname.
vagrant_hostname: local.<project>.com
vagrant_machine_name: <project>
# Set the IP address so it doesn't conflict with other Drupal VM instances.
vagrant_ip: 192.168.106.213
# Use Ubuntu 16.04 LTS to match Acquia Cloud environments.
vagrant_box: geerlingguy/ubuntu1604
# Set drupal_site_name to the project's human-readable name.
drupal_site_name: "<project>"
# Provide the path to the project root to Vagrant.
vagrant_synced_folders:
  # Set the local_path for the first synced folder to `.`.
  - local_path: .
    # Set the destination to the Acquia Cloud subscription machine name.
    destination: /var/www/<project>
    type: nfs
drupal_build_composer_project: false
# Toggling this to `true` would invoke `composer install` with the
# projects own `composer.json` successfully.
drupal_build_composer: false
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/<project>"
drupal_core_path: "/var/www/<project>/docroot"
ssh_home: /var/www/<project>
drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_name: drupal
# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
drupal_install_site: false
# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_drush_aliases: false
# This is required for front-end building tools.
nodejs_version: "6.x"
nodejs_npm_global_packages:
  - name: bower
  - name: gulp-cli
  - name: yarn
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"
installed_extras:
  - adminer
  - drush
  - mailhog
  - nodejs
  - selenium
  - solr
  - xdebug
# PHP 5.6 (PHP 7.1 is being tested, see: https://docs.acquia.com/node/25726).
php_version: "7.1"
php_packages_extra:
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-imagick"
  - imagemagick
# XDebug configuration.
# Change this value to 1 in order to enable xdebug by default.
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
# Change this value to 1 in order to enable xdebug on the cli.
php_xdebug_cli_enable: 0
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_port: "9000"
php_memory_limit: "512M"
# Acquia Search defaults to 4.5.1.
solr_version: "4.5.1"
post_provision_scripts:
  - "../../../../scripts/configure-solr.sh"
  - "../../../acquia/blt/scripts/drupal-vm/post-provision.sh"
```
