### ISSUE TITLE
Running blt setup fails

### ISSUE THREAD

**Issue by kevinquillen** [acquia/blt#2251]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.6
* BLT version: 8.9.10

Output of `blt doctor`:
```
+----------------------+----------------------------------------------------------------------------------+
| Property             | Value                                                                            |
+----------------------+----------------------------------------------------------------------------------+
| %paths               |                                                                                  |
|  - %root             | /var/www/mysite/docroot                                                 |
|  - %site             | sites/default                                                                    |
|  - %modules          | modules                                                                          |
|  - %themes           | themes                                                                           |
|  - %config-sync      | /var/www/mysite/config/default                                          |
|  - %files            | sites/default/files                                                              |
|  - %private          | /var/www/mysite/files-private                                           |
|  - %temp             | /tmp                                                                             |
| admin-theme          | seven                                                                            |
| blt-version          | 8.9.10                                                                           |
| bootstrap            | Successful                                                                       |
| config-sync          | /var/www/mysite/config/default                                          |
| db-driver            | mysql                                                                            |
| db-hostname          | localhost                                                                        |
| db-name              | drupal                                                                           |
| db-password          | drupal                                                                           |
| db-port              | 3306                                                                             |
| db-status            | Connected                                                                        |
| db-username          | drupal                                                                           |
| dev-desktop-enabled  | false                                                                            |
| drupal-settings-file | sites/default/settings.php                                                       |
| drupal-version       | 8.4.2                                                                            |
| drupal-vm-enabled    | true                                                                             |
| drush-alias-files    | /var/www/mysite/docroot/../drush/site-aliases/aliases.drushrc.php       |
|                      | /var/www/mysite/docroot/../drush/site-aliases/example.acsf.aliases.drus |
|                      | hrc.php                                                                          |
|                      | /var/www/mysite/docroot/../drush/site-aliases/example.local.aliases.dru |
|                      | shrc.php                                                                         |
| drush-conf           | /var/www/mysite/drush/drushrc.php                                       |
| drush-script         | /var/www/mysite/vendor/drush/drush/drush.php                            |
| drush-temp           | /tmp                                                                             |
| drush-version        | 8.1.15                                                                           |
| files                | sites/default/files                                                              |
| install-profile      | lightning                                                                        |
| local-drushrc        | /var/www/mysite/docroot/sites/default/local.drushrc.php                 |
| local-settings       | /var/www/mysite/docroot/sites/default/settings/local.settings.php       |
| modules              | modules                                                                          |
| php-bin              | /usr/bin/php                                                                     |
| php-conf             | /etc/php/7.1/cli/php.ini                                                         |
| php-mysql            | /var/run/mysqld/mysqld.sock                                                      |
| php-os               | Linux                                                                            |
| private              | /var/www/mysite/files-private                                           |
| root                 | /var/www/mysite/docroot                                                 |
| shell                |                                                                                  |
| site                 | sites/default                                                                    |
| temp                 | /tmp                                                                             |
| theme                | stark                                                                            |
| themes               | themes                                                                           |
| uri                  | http://local.mysite.com                                                 |
| user                 |                                                                                  |
+----------------------+----------------------------------------------------------------------------------+
+--------------------------+-----------------------------------------------------------------+
| Check                    | Outcome                                                         |
+--------------------------+-----------------------------------------------------------------+
| checkDocrootExists       | Found docroot.                                                  |
| checkCoreExists          | Drupal core exists                                              |
| checkSettingsFile        | BLT settings are included in settings file.                     |
| checkLocalSettingsFile   | Found your local settings file.                                 |
| checkLocalDrushFile      | Found your local drush settings file.                           |
| checkUri                 | $options['uri'] is set.                                         |
| checkUriResponse         | Received a response from site http://local.mysite.com. |
| checkFileSystem:%files   | Public files directory is writable.                             |
| checkFileSystem:%private | Private files directory is writable.                            |
| checkFileSystem:%temp    | Temporary files directory is writable.                          |
| checkDbConnection        | Connected to database.                                          |
| checkDrupalBootstrapped  | Bootstrapped Drupal via drush.                                  |
| checkDrupalInstalled     | Drupal is installed.                                            |
| checkCaching:page        | Drupal cache is disabled.                                       |
| checkCaching:css         | CSS preprocessing is disabled.                                  |
| checkCaching:js          | JS preprocessing is disabled.                                   |
| checkComposer:require    | acquia/blt is in composer.json's require object.                |
| checkBehat:exists        | Behat local settings file exists.                               |
| checkBehat:root          | Behat drupal_root is set correctly for Drupal VM.               |
| checkProjectYml:keys     | project.yml has no deprecated keys.                             |
| checkDrupalVm:alias      | drush.aliases.local exists your drush aliases file.             |
| checkDrupalVm            | Drupal VM is configured correctly.                              |
| checkPhpDateTimezone     | PHP setting for date.timezone is correctly set                  |
+--------------------------+-----------------------------------------------------------------+
Connection to 127.0.0.1 closed.
```

When I run this command:
```
blt setup
```

I get the following output:
```
> setup:drupal:install
Executing command blt 'setup:drupal:install' --define=drush.alias=self inside of Drupal VM...
[warning] The xDebug extension is loaded. This will significantly decrease performance.
> internal:drupal:install
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/mysite/vendor/bin/drush site-install lightning install_configure_form.update_status_module='array(FALSE,FALSE)' install_configure_form.enable_update_status_module=NULL --site-name='Mysite' --site-mail=no-reply@acquia.com --account-name=EtMI7hLh6m --account-mail=no-reply@acquia.com --locale=en --config-dir=../config/default --uri=default --yes --verbose in /var/www/mysite/docroot
Configuration import directory ../config/default does not contain any configuration; will skip import.                                                           [warning]
Executing: mysql --defaults-extra-file=/tmp/drush_LL7BSM --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_30YgCY > /dev/null
You are about to DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y
Sites directory /var/www/mysite/docroot/sites/default already exists - proceeding.                                                                         [notice]
Executing: mysql --defaults-extra-file=/tmp/drush_j8Qzrp --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_rjY49A > /dev/null
Executing: mysql --defaults-extra-file=/tmp/drush_NIKc21 --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_WW6RJd
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                     [ok]
Drupal\Core\Config\PreExistingConfigException: Configuration objects (core.entity_form_display.media.image.default, core.entity_view_display.media.image.default,[error]
media.type.image) provided by lightning_media_image already exist in active configuration in
/var/www/mysite/docroot/core/lib/Drupal/Core/Config/PreExistingConfigException.php:65
Stack trace:
#0 /var/www/mysite/docroot/core/lib/Drupal/Core/Config/ConfigInstaller.php(492):
Drupal\Core\Config\PreExistingConfigException::create('lightning_media...', Array)
#1 /var/www/mysite/docroot/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(132):
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'lightning_media...')
#2 /var/www/mysite/docroot/core/lib/Drupal/Core/Extension/ModuleInstaller.php(145):
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'lightning_media...')
#3 /var/www/mysite/docroot/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array,
false)
#4 /var/www/mysite/docroot/core/includes/install.core.inc(1812): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, false)
#5 /var/www/mysite/docroot/core/includes/batch.inc(294): _install_module_batch('lightning_media...', 'Media Image', Array)
#6 /var/www/mysite/docroot/core/includes/form.inc(875): _batch_process()
#7 /var/www/mysite/docroot/core/includes/install.core.inc(633): batch_process(Object(Drupal\Core\Url), Object(Drupal\Core\Url))
#8 /var/www/mysite/docroot/core/includes/install.core.inc(554): install_run_task(Array, Array)
#9 /var/www/mysite/docroot/core/includes/install.core.inc(117): install_run_tasks(Array)
#10 /var/www/mysite/vendor/drush/drush/includes/drush.inc(726): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#11 /var/www/mysite/vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)
#12 /var/www/mysite/vendor/drush/drush/commands/core/drupal/site_install.inc(82): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader),
Array)
#13 /var/www/mysite/vendor/drush/drush/commands/core/site_install.drush.inc(255): drush_core_site_install_version('lightning', Array)
#14 /var/www/mysite/vendor/drush/drush/includes/command.inc(422): drush_core_site_install('lightning', 'install_configu...', 'install_configu...')
#15 /var/www/mysite/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#16 /var/www/mysite/vendor/drush/drush/includes/command.inc(199): drush_command('lightning', 'install_configu...', 'install_configu...')
#17 /var/www/mysite/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#18 /var/www/mysite/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#19 /var/www/mysite/vendor/drush/drush/drush.php(12): drush_main()
#20 {main}
Command dispatch complete                                                                                                                                           [notice]
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 59.749s
[error]  Failed to install Drupal! 
[error]  Command `internal:drupal:install ` exited with code 1. 
Connection to 127.0.0.1 closed.
```

And I expected this to happen:

Drupal 8 to install.

I have destroyed the VM and started from scratch many times today and always wind up back in this same spot.

VM config:

```
# Update the hostname to the local development environment hostname.
vagrant_hostname: local.mysite.com
vagrant_machine_name: mysite

# Set the IP address so it doesn't conflict with other Drupal VM instances.
vagrant_ip: 0.0.0.0

# Use Ubuntu 16.04 LTS to match Acquia Cloud environments.
vagrant_box: geerlingguy/ubuntu1604

# Set drupal_site_name to the project's human-readable name.
drupal_site_name: "Mysite"

# Provide the path to the project root to Vagrant.
vagrant_synced_folders:
  # Set the local_path for the first synced folder to `.`.
  - local_path: .
    # Set the destination to the Acquia Cloud subscription machine name.
    destination: /var/www/mysite
    type: nfs

drupal_build_composer_project: false
# Toggling this to `true` would invoke `composer install` with the
# projects own `composer.json` successfully.
drupal_build_composer: false
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/mysite"
drupal_core_path: "/var/www/mysite/docroot"
ssh_home: /var/www/mysite

drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_name: drupal

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
drupal_install_site: false

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_drush_aliases: false

# This is required for front-end building tools.
nodejs_version: "6.x"
nodejs_npm_global_packages:
  - name: bower
  - name: gulp-cli
  - name: yarn
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"
installed_extras:
  #- adminer
  - drush
  - mailhog
  - memcache
  - nodejs
  #- solr
  #- selenium
  - xdebug

# PHP 5.6 (PHP 7.1 is being tested, see: https://docs.acquia.com/node/25726).
php_version: "7.1"
php_install_recommends: no
php_memory_limit: "256M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/opt/mailhog/mhsendmail"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

php_packages_extra:
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-imagick"
  - imagemagick

# XDebug configuration.
# Change this value to 1 in order to enable xdebug by default.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 0
# Change this value to 1 in order to enable xdebug on the cli.
php_xdebug_cli_enable: 0
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_port: "9000"

post_provision_scripts:
  - "../../../acquia/blt/scripts/drupal-vm/post-provision.sh"
```

I am not doing anything different than I normally do, but this _is_ my first time using Lightning.
