### ISSUE TITLE
Composer patches should exit on failure when running composer commands directly

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2316]
Currently when BLT runs composer install as part of the build step, it sets the env var COMPOSER_EXIT_ON_PATCH_FAILURE=1, which forces composer patches to abort the install on failure. This is awesome, but it leaves people in the lurch when running composer install outside of BLT. If composer-patches fails in this context, it will throw an error but not so obviously as aborting the install.

After the next release of composer-patches, we can instead add a key to composer.json:
https://github.com/cweagans/composer-patches/pull/166

Things to consider:
* Do we need to update existing projects to use this key
* If BLT simply includes the key in its own composer files, will it be inherited by downstream projects
* We'll want to verify that this key is present, presumably as part of blt doctor and/or the composer validation step
* Consider whether it makes sense to remove the env var from the build step... it should be unnecessary, but there's not much harm in leaving it, and it might be a good "belt and suspenders" safety.

**Comment by danepowell** [comment]
Looks like we already tried to fix this for deployments in https://github.com/acquia/blt/issues/705

**Comment by grasmash** [comment]
I have confirmed that inheritance works as expected.

**Comment by loopy3025** [comment]
I am trying to incrementally upgrad BLT from 8 to 9 then 10. On the 8-9 step, It's trying to install 

```    https://www.drupal.org/files/issues/2788777-3-146.patch (Allow a site-specific profile to be installed from existing config)
```
Which doesn't apply to the version of Drupal it's trying to install (8.7.7). Ostensibly, BLT 9.2.8 is supposed to be compatible with drupal core ^8.7.x

So, I added this to my composer file:
```

        "composer-exit-on-patch-failure": false,
        "patches-ignore": {
            "drupal/core": {
                "Allow a site-specific profile to be installed from existing config": "https://www.drupal.org/files/issues/2788777-3-146.patch"
            }
``` 
Which does work when building locally, but when I try to push it through pipelines, it throws an error.  I tried adding the variable declaration to my acquia-pipelines.yml file, but that seems not to have worked either.

```
variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    BLT_DIR: $SOURCE_DIR/vendor/acquia/blt
    COMPOSER_EXIT_ON_PATCH_FAILURE: 0
```
and
```
        - setup-app:
            type: script
            script:
              - COMPOSER_EXIT_ON_PATCH_FAILURE=0
              - source ${BLT_DIR}/scripts/pipelines/setup_app
```
How can I set the exit on patch to false when building with BLT?
