### ISSUE TITLE
How to sync from different remote sources?

### ISSUE THREAD

**Issue by kevinquillen** [acquia/blt#2325]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.6
* BLT version: 8.9.10

When I run this command:
```
blt sync:refresh
```

Is there a way to add on to this command to tell it which source to sync from? In project.yml, I have this:

```
drush:
  aliases:
    remote: '${project.machine_name}.test'
    local: self
    ci: self
```

Short of changing the remote property, is there a way to add dev, test, and prod to sync down from?
