### ISSUE TITLE
Disabling BLT commit message

### ISSUE THREAD

**Issue by justinlevi** [acquia/blt#2582]
Bringing back an old issue...
https://github.com/acquia/blt/issues/2128

My system information:
* Operating system type: Mac OSX 10.13.3
* BLT version: 9.0-beta2 ----> 9.0-beta3

Output of `blt doctor`:
```
+---------------------------+--------------------------------------------------------------+
| Property                  | Value                                                        |
+---------------------------+--------------------------------------------------------------+
| %paths.%root              | /Users/justinwinter/Sites/d8d/docroot                        |
| %paths.%site              | sites/default                                                |
| %paths.%modules           | sites/all/modules                                            |
| %paths.%themes            | sites/all/themes                                             |
| %paths.%config-sync       | /Users/justinwinter/Sites/d8d/config/default                 |
| %paths.%files             | sites/default/files                                          |
| %paths.%temp              | /tmp                                                         |
| %paths.%private           | /Users/justinwinter/Sites/d8d/files-private                  |
| admin-theme               | seven                                                        |
| alias-searchpaths.0       | /Users/justinwinter/Sites/d8d/drush/sites                    |
| blt-version               | 9.0.0-beta3                                                  |
| bootstrap                 | Successful                                                   |
| composer-version          | Composer version 1.5.2 2017-09-11                            |
|                           | 16:59:25                                                     |
| config-sync               | /Users/justinwinter/Sites/d8d/config/default                 |
| db-driver                 | mysql                                                        |
| db-hostname               | localhost                                                    |
| db-name                   | d8d                                                          |
| db-password               | drupal                                                       |
| db-port                   | 3306                                                         |
| db-status                 | Connected                                                    |
| db-username               | drupal                                                       |
| drupal-settings-file      | sites/default/settings.php                                   |
| drupal-version            | 8.5.0-rc1                                                    |
| drush-alias-files.0       | /Users/justinwinter/Sites/d8d/drush/sites/d8d.site.yml       |
| drush-conf.0              | /Users/justinwinter/Sites/d8d/vendor/drush/drush/drush.yml   |
| drush-conf.1              | /Users/justinwinter/Sites/d8d/drush/drush.yml                |
| drush-conf.2              | /Users/justinwinter/Sites/d8d/docroot/sites/default/local.dr |
|                           | ush.yml                                                      |
| drush-script              | /Users/justinwinter/Sites/d8d/vendor/bin/drush               |
| drush-temp                | /tmp                                                         |
| drush-version             | 9.2.0                                                        |
| files                     | sites/default/files                                          |
| install-profile           | d8d                                                          |
| modules                   | sites/all/modules                                            |
| php-bin                   | /usr/local/Cellar/php71/7.1.10_21/bin/php                    |
| php-conf.0                | /usr/local/etc/php/7.1/php.ini                               |
| php-os                    | Darwin                                                       |
| private                   | /Users/justinwinter/Sites/d8d/files-private                  |
| root                      | /Users/justinwinter/Sites/d8d/docroot                        |
| site                      | sites/default                                                |
| stacks.drupal-vm.inited   | false                                                        |
| stacks.dev-desktop.inited | false                                                        |
| temp                      | /tmp                                                         |
| theme                     | bartik                                                       |
| themes                    | sites/all/themes                                             |
| uri                       | http://d8d.loc                                               |
+---------------------------+--------------------------------------------------------------+
+--------------------------------------+--------------------------------------------------------------+
| Check                                | Problem                                                      |
+--------------------------------------+--------------------------------------------------------------+
| ConfigCheck:checkGitConfig           | Git repositories are not defined in blt.yml.                 |
|                                      |   Add values for git.remotes to blt.yml to enabled automated |
|                                      | deployment.                                                  |
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root.    |
+--------------------------------------+--------------------------------------------------------------+
```

When I run this command:
```
$ `git commit -m "blt upgrade and travis config"`
```

I get the following output:
```
Executing .git/hooks/pre-commit...
Executing .git/hooks/commit-msg...
Validating commit message syntax...
PHP Warning:  preg_match(): Empty regular expression in /Users/justinwinter/Sites/d8d/vendor/acquia/blt/src/Robo/Commands/Git/GitCommand.php on line 25

Warning: preg_match(): Empty regular expression in /Users/justinwinter/Sites/d8d/vendor/acquia/blt/src/Robo/Commands/Git/GitCommand.php on line 25
[error]  Invalid commit message! 
Commit messages must conform to the regex 
[notice] To disable this command, see http://blt.rtfd.io/en/8.x/readme/extending-blt/#disabling-a-command
[notice] To customize git hooks, see http://blt.rtfd.io/en/8.x/readme/extending-blt/#setupgit-hooks.
soundslides:d8d justinwinter$ git commit -m "blt upgrade and travis config"

```

And I expected this to happen:

I expect the pre-commit requirement to be ignored. 

Here is my `blt.yml`, including the disable-targets and git hooks > pre-commit configuration settings that worked prior to the update. 

```
project:
  machine_name: d8d
  prefix: BLT
  human_name: 'BLTed 8'
  profile:
    name: lightning
  local:
    protocol: http
    hostname: 'local.${project.machine_name}.com'
git:
  default_branch: master
  remotes: {  }
  pre-commit: false
  commit-msg: false
  hooks:
    pre-commit: false
drush:
  aliases:
    remote: '${project.machine_name}.test'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
modules:
  local:
    enable: [dblog, devel, seckit, views_ui]
    uninstall: [acquia_connector, shield]
  ci:
    enable: {  }
    uninstall: [acquia_connector, shield]
  dev:
    enable: [acquia_connector, shield]
    uninstall: {  }
  test:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
  prod:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
disable-targets:
  validate:
    phpcs: true
  git:
    commit-msg: true
    pre-commit: true
```

**Comment by grasmash** [comment]
Does `vendor/acquia/blt/config/build.yml` contain a value for `git.commit-msg.pattern`?

https://github.com/acquia/blt/blob/9.x/config/build.yml#L96

**Comment by justinlevi** [comment]
I realize I might be in the minority here, but I'm wondering if it might make more sense to disable the commit messages by default and make it optional to turn them on. Feels a bit heavy handed to me to require a commit message. From my experience, this is a self policing issue in that really bad commit messages are pretty useless and should be encouraged against as a culture.

**Comment by justinlevi** [comment]
@grasmash Yes, it does. 

```
git:
  # The value of a hook should be the file path to a directory containing an
  # executable file named after the hook.
  # Changing a hook value to 'false' will disable it.
  hooks:
    pre-commit: ${blt.root}/scripts/git-hooks
    commit-msg: ${blt.root}/scripts/git-hooks
  commit-msg:
    # Commit messages must conform to this pattern.
    pattern: "/(^${project.prefix}-[0-9]+(: )[^ ].{15,}\\.)|(Merge branch (.)+)/"
```
