### ISSUE TITLE
Frontend builds not working, no hook is defined

### ISSUE THREAD

**Issue by timwood** [acquia/blt#2629]
My system information:
* Operating system type: Mac / Drupal VM 4.8.1
* Operating system version: Sierra / beet/box
* BLT version: 9.0.3

Output of `blt doctor`:
```
$ blt doctor
[warning] The xDebug extension is loaded. This will significantly decrease performance.
+---------------------------+---------------------------------------------------------+
| Property                  | Value                                                   |
+---------------------------+---------------------------------------------------------+
| %paths.%root              | /var/www/mfgov-d8/docroot                               |
| %paths.%site              | sites/default                                           |
| %paths.%modules           | sites/all/modules                                       |
| %paths.%themes            | sites/all/themes                                        |
| %paths.%config-sync       | /var/www/mfgov-d8/config/default                        |
| %paths.%files             | sites/default/files                                     |
| %paths.%temp              | /tmp                                                    |
| %paths.%private           | /var/www/mfgov-d8/files-private                         |
| admin-theme               | seven                                                   |
| alias-searchpaths.0       | /var/www/mfgov-d8/drush/sites                           |
| blt-version               | 9.0.3                                                   |
| bootstrap                 | Successful                                              |
| composer-version          | Composer version 1.6.3 2018-01-31 16:28:17              |
| config-sync               | /var/www/mfgov-d8/config/default                        |
| db-driver                 | mysql                                                   |
| db-hostname               | localhost                                               |
| db-name                   | drupal                                                  |
| db-password               | drupal                                                  |
| db-port                   | 3306                                                    |
| db-status                 | Connected                                               |
| db-username               | drupal                                                  |
| drupal-settings-file      | sites/default/settings.php                              |
| drupal-version            | 8.5.0                                                   |
| drush-alias-files.0       | /var/www/mfgov-d8/drush/sites/mfgov.site.yml            |
| drush-conf.0              | /var/www/mfgov-d8/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/mfgov-d8/drush/drush.yml                       |
| drush-conf.2              | /var/www/mfgov-d8/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/mfgov-d8/vendor/bin/drush                      |
| drush-temp                | /tmp                                                    |
| drush-version             | 9.2.1                                                   |
| files                     | sites/default/files                                     |
| install-profile           | lightning                                               |
| modules                   | sites/all/modules                                       |
| php-bin                   | /usr/bin/php7.1                                         |
| php-conf.0                | /etc/php/7.1/cli/php.ini                                |
| php-os                    | Linux                                                   |
| private                   | /var/www/mfgov-d8/files-private                         |
| root                      | /var/www/mfgov-d8/docroot                               |
| site                      | sites/default                                           |
| stacks.drupal-vm.inited   | true                                                    |
| stacks.dev-desktop.inited | false                                                   |
| temp                      | /tmp                                                    |
| theme                     | uswds_mfgov                                             |
| themes                    | sites/all/themes                                        |
| uri                       | https://local.manufacturing.test                        |
+---------------------------+---------------------------------------------------------+
+--------------------------------------+-----------------------------------------------------------+
| Check                                | Problem                                                   |
+--------------------------------------+-----------------------------------------------------------+
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root. |
| WebUriCheck:checkHttps               | The SSL certificate for your local site appears to be     |
|                                      | invalid for https://local.manufacturing.test.             |
+--------------------------------------+-----------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues. 
```

When I run this command (or any of the individual sub commands):
```
blt -vvv source:build:frontend
```

I get the following output:
```
[warning] The xDebug extension is loaded. This will significantly decrease performance.
> source:build:frontend-reqs
[info] Skipped frontend-reqs target hook. No hook is defined.
> source:build:frontend-assets
[info] Skipped frontend-assets target hook. No hook is defined.
0.645s total time elapsed.
```

And I expected this to happen:
Front end setup and build commands to run. Here is what I have defined in `blt/blt.yml`:

```
command-hooks:
  source:build:frontend-reqs:
    dir: ${docroot}/themes/custom/uswds_mfgov
    command: 'npm install'
  source:build:frontend-assets:
    dir: ${docroot}/themes/custom/uswds_mfgov
    command: 'npm run build'
```

Also, I had to manually update my `blt/blt.yml` for the changes between BLT 8.9.x to 9.x (target-hooks -> command-hooks, etc.). Should the BLT upgrade process attempt to handle this?

**Comment by grasmash** [comment]
The hooks are:

- command-hooks.frontend-assets
- command-hooks.frontend-reqs
- command-hooks.frontend-test

The commands to run those hooks are:

- blt source:build:frontend-assets
- blt source:build:frontend-reqs
- blt tests:frontend:run

Your blt.yml should contain:
```
command-hooks:
  frontend-reqs:
    dir: ${docroot}/themes/custom/uswds_mfgov
    command: 'npm install'
  frontend-assets:
    dir: ${docroot}/themes/custom/uswds_mfgov
    command: 'npm run build'
```

**Comment by timwood** [comment]
Thanks for clarifying that. Should the docs be updated to reflect that here: http://blt.readthedocs.io/en/stable/readme/frontend/#setup ?

We were following the changes to that page, from the 8.9.x version.

**Comment by grasmash** [comment]
Yes, thank you. That's a documentation error.

**Comment by timwood** [comment]
Thanks!

**Comment by justclint** [comment]
@grasmash we just upgraded to BLT 9 and this fixed our issue. Just wanted to get clarification though as I didnt see a reference in the current documentations. We still have the hooks left over from last version:

```
  pre-config-import:
    dir: '${docroot}'
    command: 'echo ''No pre-config-import configured.'''
  post-deploy-build:
    dir: '${docroot}'
    command: 'echo ''No post-deploy build configured.'''
  post-setup-build:
    dir: '${docroot}'
    command: 'echo ''No post-setup build configured.'''
  post-deploy:
    dir: '${docroot}'
    command: 'echo ''No post-deploy build configured.'''
  custom-post-config:
```

Are these hook names need to be updated or are they even used anymore?

Thanks!
