### ISSUE TITLE
Allow for multiple project prefixes to be used

### ISSUE THREAD

**Issue by leonk** [acquia/blt#2667]
When working with BLT, quite often the codebase will span multiple projects in Jira.  This could be due to a number of reasons:
- The project spans multiple sites and they are separated into different Jira spaces (typically when using site factory).
- Different Jira boards are setup to track bugs, new features etc.

It would be nice to be able to specify multiple prefixes, that are all allowed as a git commit message.

E.g.
```
  prefix: FOO|BAR
```

This would prevent having to override project.yml, or constantly update project.local.yml.

**Comment by grasmash** [comment]
This can already be accomplished using existing features by setting `git.commit-msg.pattern` in blt.yml:

```
git:
  commit-msg:
    # Commit messages must conform to this pattern.
    pattern: "/(^(FOO|BAR)-[0-9]+(: )[^ ].{15,}\\.)|(Merge branch (.)+)/"
```
