### ISSUE TITLE
Remove git hooks when disabled in blt.yml

### ISSUE THREAD

**Issue by mortona42** [acquia/blt#2697]
I disabled the commit-msg hook in blt.yml. I think this should remove the hook when blt:init:git-hooks is run.

blt.yml:
```
git:
  default_branch: master
  remotes: {  }
  hooks:
    commit-msg: false
```

When I run this command:
```
blt big
```

I get the following output:
```
Installing pre-commit git hook...
Skipping installation of commit-msg git hook
```

And I expected this to happen:
Remove the hook if it was installed previously.
