### ISSUE TITLE
DT-598: Yaml placeholders are not correctly expanded in runtime parameters

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2722]
My system information:
* BLT version: 9.0.5

I've defined the following command hook:
```yml
command-hooks:
 post-deploy-build:
   dir: '${deploy.dir}'
   command: 'rm -rf vendor/drush'
```

BLT builds artifacts on Pipelines by calling this:
```bash
export NEW_BUILD_DIR=/tmp/artifact
blt artifact:build -D deploy.dir=${NEW_BUILD_DIR} --ansi --verbose
```

Thus, I would expect the `rm` command I've defined to run in `/tmp/artifact`. Instead, it actually runs in the Pipelines source directory. This is bad, because the changes to that directory don't get preserved. So as near as I can tell, the post-deploy-build hook is useless.

As a workaround, I've hardcoded the directory to be `/tmp/artifact` but that's obviously not sustainable.
