### ISSUE TITLE
Twig lint fails on twig_tweak functions

### ISSUE THREAD

**Issue by brooke-heaton** [acquia/blt#2815]
I'm unclear on how to exclude twig_tweak functions from the `asm89/twig-lint` process. I am specifically using the `drupal_field` function provided by twig_tweak: https://www.drupal.org/docs/8/modules/twig-tweak/cheat-sheet-8x-2x (https://cgit.drupalcode.org/twig_tweak/tree/src/TwigExtension.php?h=8.x-2.x). Do I simply need to exclude this linting or can I ignore twig_tweak functions somehow?

  ERROR  in 
```
docroot/themes/custom/my_custom_theme/templates/paragraph/paragraph--landing-teaser.html.twig (line 10)
      8              {% set nid = content.field_shortcut_url.0['#plain_text'] %}
      9              {% set slink = "node/" ~ nid %}
  >>  10             {% set stitle = drupal_field('title', 'node', nid) %}
  >> Unknown "drupal_field" function. 
      11     {% endif %}
      12     

```

**Comment by brooke-heaton** [comment]
Would love to see better documentation/support for BLT by Acquia in general. Honestly this is the only tool I have for CD/CI and the support is pretty bad.

**Comment by dpagini** [comment]
Does this work for you...?

**In blt.yml:**
```yml
validate:
  twig:
    functions:
      - drupal_block
      - drupal_field
```

**Comment by wu-edward** [comment]
Documentation for excluding additional Twig functions and filters is here:
https://blt.readthedocs.io/en/latest/readme/extending-blt/#teststwiglintall

Please provide suggestions (or a PR) if you have thoughts on how this can be improved.

**Comment by brooke-heaton** [comment]
@dpagini @wu-edward Thanks so much for pointing this out. I'm still ramping up and didn't see this documentation.

**Comment by brooke-heaton** [comment]
Fro those following along, I'm hoping these exclusions help:

```
validate:
  twig:
    functions:
      - drupal_block
      - drupal_field
      - drupal_view
      - drupal_block
      - drupal_region
      - drupal_entity
      - drupal_field
      - drupal_menu
      - drupal_form
      - drupal_image
      - drupal_token
      - drupal_config
      - drupal_title
      - drupal_url
      - drupal_link
      - drupal_messages
      - drupal_breadcrumb
```
