### ISSUE TITLE
BLT Behat/Pipelines integration giving wrong HTTP response code

### ISSUE THREAD

**Issue by anavarre** [acquia/blt#2827]
## Local

With the default `Examples.feature` Behat test that ships with BLT, I'm getting a failure locally, since my site is authenticated only and behind SAML. Loading the homepage thus correctly returns a 403 (Access Denied).

```
Scenario: Load a page without Javascript
  Given I am on "/"
  Then the response status code should be 200
    Current response status code is 403, but 200 expected.
```
When I edit the test to check for a 403 instead, it works instantly.

```
Scenario: Load a page without Javascript
  Given I am on "/"
  Then the response status code should be 403
```
## Pipelines

With the same exact setup on Pipelines (and the un-edited test), I'm getting a different and wrong 200 response code.

```
Scenario: Load a page without Javascript 
  Given I am on "/"
  Then the response status code should be 200
```

When you hit the site as anon over a cURL-like CLI it correctly returns the 403:

```
$ http -h https://site.tld | grep HTTP
HTTP/1.1 403 Forbidden
```

**Comment by anavarre** [comment]
@mikemadison13 do you have enough details to address this issue?

**Comment by mikemadison13** [comment]
@anavarre sorry for the delay! 

a few thoughts here. 

first of all, you are welcome to get rid of that example test. there is no reason to keep it (or change it). the test itself is legit in a non-saml scenario, so i am hesitant to change it on the BLT side.

second of all, it might make sense to disable saml locally and in ci using config splits. this might help work around the issue locally as well.

do either of those suggestions help?

**Comment by anavarre** [comment]
@mikemadison13 I would in theory remove that example test. Actually I initially had, thus why I didn't see the issue immediately.

What I'm getting at is while `config_split` _might_ help (so far it didn't in my testing where I want to shutdown SAML entirely with Pipelines) the real issue we have here is the test is doing something very simple (checking a HTTP response code) but behaving differently whether you're on local or Pipelines.

For months, and before we even cared about Behat, we had this test to pass successfully while it was trying to check for a 200 that was actually a 403 always (remember: site is 100% behind SAML).

That's this issue I think we should focus on for now. Does that make sense?

**Comment by anavarre** [comment]
@mikemadison13 I've been performing additional testing and still find there's an issue with the HTTP response code.

Context: **all pages on the site should return a 403 as anon since the site is 100% behind SAML**.

Here's my example Behat test:

```
@example
Feature: Web drivers
  In order to verify that web drivers are working
  As a user
  I should be able to load the homepage
  With and without Javascript

  @javascript
  Scenario: Load a page with Javascript
    Given I am on "/"
    Then I should be on "/"

  Scenario: Load a page without Javascript
    Given I am on "/"
    Then the response status code should be 200

  Scenario: PAGE IS A 403
    Given I am on "/faq"
    Then the response status code should be 403
```

As you can see I'm simply extending the sample Behat test that ships with BLT. My issue is the default scenarios should **never** pass in the first place since the site is returning an Access Denied (403) for anonymous users, but Behat is passing with a 200.

At the bottom of the file, I've added a test for a different page than `/` which should also return a 403. You'll notice it returns a 404 below. So this means both `/` and `/faq` are wrong, but with 2 different HTTP response codes.

Here's what I'm seeing in practice with Pipelines:

```
[info] Launching headless chrome...
[Robo\Common\ProcessExecutor] Running 'google-chrome' --headless --disable-web-security --remote-debugging-port=9222  http://localhost in /mnt/tmp/local.prod/source

[info] Waiting for response from http://localhost:9222...

[info] Waiting for response from http://localhost:9222...

[Testing\Behat] Running behat  --format pretty /mnt/tmp/local.prod/source/tests/behat --colors --no-interaction --stop-on-failure --strict --config /mnt/tmp/local.prod/source/tests/behat/local.yml --profile local --tags '~ajax&&~experimental&&~lightningextension' -v

@example
Feature: Web drivers
  In order to verify that web drivers are working
  As a user
  I should be able to load the homepage
  With and without Javascript

  @javascript
  Scenario: Load a page with Javascript # features/Examples.feature:9

    Given I am on "/"
    Then I should be on "/"

  Scenario: Load a page without Javascript
    Given I am on "/"
    Then the response status code should be 200

  Scenario: TEST
    Given I am on "/faq"
    Then the response status code should be 200
      Current response status code is 404, but 200 expected.
```

I should have 100% failure, but Behat returns only one failure for the last test. This is very confusing and not the expected / anticipated behavior. Also pinging @lcatlett since she's been talking this through with us previously.

**Comment by mikemadison13** [comment]
@anavarre I'm curious, is this happening locally as well or just on Pipelines?

**Comment by mikemadison13** [comment]
i would also be curious if you manually execute this test in chrome, what chrome reports the error code to be.

**Comment by anavarre** [comment]
> is this happening locally as well or just on Pipelines?

@mikemadison13 It's only happening with Pipelines. Here's an excerpt of a local test run with the same exact file.

```
@example
Feature: Web drivers
  In order to verify that web drivers are working
  As a user
  I should be able to load the homepage
  With and without Javascript

  @javascript
  Scenario: Load a page with Javascript # features/Examples.feature:9
    Given I am on "/"
    Then I should be on "/"

  Scenario: Load a page without Javascript
    Given I am on "/"
    Then the response status code should be 200
      Current response status code is 403, but 200 expected.
```

The failure is normal as behind SAML a 403 is expected. If I shut down SAML in any way, then the tests will pass with a 200.

> i would also be curious if you manually execute this test in chrome, what chrome reports the error code to be.

Could you please advise how to achieve this? I'm happy to report back with the output once I know what's expected exactly.

**Comment by mikemadison13** [comment]
closing due to inactivity

**Comment by anavarre** [comment]
@mikemadison13 still a thing - What missing information do you need?

**Comment by mikemadison13** [comment]
we need someone to run with this and try to get it fixed if still happening. might be something @alexxed could try and reproduce.

**Comment by danepowell** [comment]
@anavarre what makes you think that this is a problem with BLT / Behat? If it says that Drupal is returning a 200 for that page, I would generally trust that it _is_ in fact returning a 200.

I suspect something about your configuration is in fact allowing anonymous visitors to access the  homepage. Maybe something related to Config Split? Maybe a conditional in one of your settings.php files that is behaving differently when it's in an Acquia environment?

We'll need some more solid info or testing steps to be able to reproduce this.

**Comment by alexxed** [comment]
It does looks like an environment difference like @danepowell said. What we should make sure here is that it's not BLT that is doing things differently.

@anavarre we need to reproduce locally as well in order to fix this. Can you share
- the acquia-pipelines file
- the behat.yml file
- the exact command you're using locally to run tests including if you're inside a vm/docker ?

**Comment by anavarre** [comment]
@danepowell 

> what makes you think that this is a problem with BLT / Behat?

I'm not saying that's necessarily BLT / Behat. Could very well be Pipelines, but I need confirmation first you can reproduce.

@alexxed

Here's `acquia-pipelines.yml`:

```
version: 1.1.0
services:
  - mysql
  - php:
      version: 7.2

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    BLT_DIR: $SOURCE_DIR/vendor/acquia/blt

events:
  build:
    steps:
        - setup-env:
            type: script
            script:
              - composer validate --no-check-all --ansi
              - composer install --ansi
              - source ${BLT_DIR}/scripts/pipelines/setup_env
              # - nvm install v6.9.1
              # - npm install --global yarn
        - validate:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/validate
        # Uncomment these lines to test database updates using live content.
        # - test-updates:
        #     type: script
        #     script:
        #       - blt drupal:sync:default:site
        - setup-app:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/setup_app
        - tests:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/tests
        - build-artifact:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/build_artifact
  post-deploy:
    steps:
      - deploy:
          script:
            - pipelines-deploy
  pr-merged:
    steps:
      - deploy:
          script:
            - pipelines-deploy
  pre-closed:
    steps:
      - deploy:
          script:
            - pipelines-deploy
```

Here's `./tests/behat/behat.yml` (is this the one you want?):

```
default:
  suites:
    default:
      paths:
        - %paths.base%/features
  extensions:
    Behat\MinkExtension:
      default_session: goutte
      browser_name: chrome
      javascript_session: default
      goutte: ~
      files_path: "%paths.base%/media"
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: "drupal"
    jarnaiz\JUnitFormatter\JUnitFormatterExtension:
        filename: report.xml
        outputDir: %paths.base%/build/tests
    Bex\Behat\ScreenshotExtension:
      screenshot_taking_mode: failed_steps
      image_drivers:
        local:
          screenshot_directory: /tmp
```

The exact command I'm running inside [drucker](https://github.com/anavarre/drucker) is:

`./vendor/acquia/blt/bin/blt behat --site=multisite.domain.com` (domain is sanitized)

-----

What I'm seeing with Pipelines is my Behat tests pass always even if a) the site is fully authenticated ONLY and Behind SAML auth and b) the example Behat test that ships with BLT is running anonymously.

However, locally I'm seeing the expected behavior which is to fail running the example Behat test since the homepage returns a 403:

```
Scenario: Load a page without Javascript      # features/Examples.feature:13
Given I am on "/"                           # Drupal\DrupalExtension\Context\MinkContext::visit()
Then the response status code should be 200 # Drupal\DrupalExtension\Context\MinkContext::assertResponseStatus()
Current response status code is 403, but 200 expected.
```

As soon as I remove the example Behat test from my Behat Features locally, all tests pass successfully.
