### ISSUE TITLE
Why does BLT require a local behat config file?

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#2860]
We're trying to simplify our behat config files and just use the main `behat.yml` config file instead of also using the `local.yml` that BLT generates.  The reasoning: In my project, we use a docker container for local development and use the same exact container setup for our CI/testing infrastructure, so no matter where the tests are run, the config will always be the same. 

My initial understanding of this is that I could just put stuff in the `local.yml` file if I wanted to _override_ configuration from the main config file, but that's not the case. BLT actually requires that this file exist and it even checks for specific configuration from that file.

**Comment by bkosborne** [comment]
OK, so the problem is actually that BLT defaults to telling Behat to use the config profile of 'local'. I changed this to 'default', but there are other hurdles. There's several areas in the BLT code that checks to ensure that certain config items exist in the local profile. So to satisfy it, I need this minimum config for my `local.yml` file:

```
# To generate a local.yml file using this the example template, execute:
# `blt setup:behat` from the project root.
imports:
  - behat.yml

local:
  suites:
    default:
      paths:
        features: ${repo.root}
        bootstrap: ${repo.root}/tests/behat/features/bootstrap
  extensions:
    Behat\MinkExtension:
      base_url: ${project.local.uri}
    Drupal\DrupalExtension:
      drupal:
        drupal_root: ${docroot}
```

Even tho Behat ultimately doesn't use any of it.

I think all of those BLT checks should take defined profile into account. So, it can check that those config items exist still, but it shouldn't assume that you have a 'local' profile.

**Comment by ba66e77** [comment]
Thanks for noting this, @bkosborne. I imagine it will be a more common issue as people move more to docker for local development. At the moment this feels like kind of an edge-case, but maybe it makes sense to consider parameterizing the profile more.

**Comment by lpeabody** [comment]
Yeah, `blt tests:behat` on BLT 9.x is completely unusable if you're running a multisite with different Behat profiles per site. I have a blt.yml in each of my site folders and they each have configuration similar to the following:

```
behat:
  config: ${repo.root}/tests/behat/profiles/bax_commercial/commercial.yml
  profile: commercial
  web-driver: phantomjs
```

I do not use local.yml at all, so the validation check fails every time when you try to run `blt tests:behat`. Any suggestions on how to work around this? This was working fine on 8.x so I would honestly consider this a very large regression.

**Comment by dpagini** [comment]
I'm not sure I see this as a docker issue... why does it seem like docker? Wouldn't this just be anyone who is using BLT for multisite?

**Comment by bkosborne** [comment]
It's not a Docker issue, but people that use Docker for local development are likely to use the same docker images in their CI environment as well, which means they may not need the concept of a "local" environment override for test configurations.

**Comment by brooke-heaton** [comment]
@lpeabody I feel your pain. Any support for Behat with multisite would be greatly appreciated. BLT is somewhat hostile toward multisite users.

**Comment by brooke-heaton** [comment]
Related to #3445

**Comment by danepowell** [comment]
The reason that local.yml is separate from the main behat.yml and must exist is because local.yml contains several placeholder tokens that need to be replaced with BLT configuration values each time it is (re)generated. I understand the desire to streamline these into a single file, but that's not generalizable across projects that do need local.yml to be dynamic. 

I can't think of a great way to satisfy both use cases. Given that, I think it's best to keep the current solution, which allows local overrides for those projects that need them, and shouldn't harm projects like the OP's that don't need them (even if it's not the most elegant).

If anyone knows of a solution that I don't and wants to submit a PR, it would be welcome.

**Comment by lpeabody** [comment]
I'll put something together.

Just curious, when you say:

> generalizable across projects that do need local.yml to be dynamic

What do you mean by dynamic?

**Comment by danepowell** [comment]
A project might need to use a different base url or selenium / chrome port on different testing environments, for instance. These values can be passed in via the CLI (`blt tests:behat -d behat.whatever`) or set via `blt.yml`, but in order for them to actually take effect they must also be written into the corresponding tokens in example.local.yml.

**Comment by brooke-heaton** [comment]
Hm, I'm confused. Site specific base urls do not work at all - the base url is only configurable in the local configuration and we have to rewrite the setting on Travis builds using yaml-cli. The local file is the only place where a base url can be defined. Am I missing something?

**Comment by lpeabody** [comment]
I can see a few scenarios that might work. I think BLT should do one of three things:

1) Completely own local.yml and have every execution of Behat run against that configuration file, by regenerating local.yml based off a given sites default.local.yml every time `blt tests:behat` runs , or
2) Work on adding flexibility and maintain validation. This could probably be done by removing hardcoded references of local.yml, and the path to base_url in Behat config and utilize BLT configuration values to generate the paths dynamically, or
3) Tell BLT to skip any and all validation of Behat configuration and just run the command as it is generated by BLT configuration.

For the sake of simplicity, option 3 would be my first choice (it's also the easiest to implement, I already have a working instance of it). It would allow BLT to continue operating as it currently is, or you could opt to disable validation and just have BLT generate the `behat` command and run it. If the command fails because configuration was not properly setup, that's on me and I chose for it to be on me.

If option 3 is not desirable, option 2 would be my next choice to pursue to see if it can be done in a reasonable and commonsensical way. It would allow sites to maintain their own dedicated profiles and BLT could still validate those profiles to ensure they're running against the proper host. I'm not sure how generating missing configuration files would work though. By far the biggest development effort.

Option 1 would be my least favorite choice, as it personally feels a bit hacky to me. However, I do believe that would be fairly simple to implement.

**Comment by danepowell** [comment]
@brooke-heaton in a standard multisite BLT setup, you have separate directories under `docroot/sites` for each site. Each directory has its own `blt.yml`, each with its own value for `project.local.hostname`. If you've set it up that way, then you shouldn't need to modify anything related to Behat, BLT will take care of the rest for you.

For instance, if you have a site `bar` with local uri `http://local.bar.com`, then running `blt tests:behat --site=bar` will rewrite local.yml such that the base_url is `http://local.bar.com`. I just tested this to verify it works exactly as expected.

The only thing is that if you are doing this in a non-interactive environment, you may have to use `-y` or `-n` with `blt tests:behat` to force the file to be regenerated.

**Comment by danepowell** [comment]
I'm about to merge a couple PRs related to this. I think the next step will be documentation fixes, which we'll address in #3690

**Comment by brooke-heaton** [comment]
> For instance, if you have a site `bar` with local uri `http://local.bar.com`, then running `blt tests:behat --site=bar` will rewrite local.yml such that the base_url is `http://local.bar.com`. I just tested this to verify it works exactly as expected.

I have never once seen this working. I have my configuration EXACTLY as described. Each time I run `blt tests:behat:run --site=naswa` I get the following error:

```
[warning] Behat is not configured properly.
BLT can (re)generate tests/behat/local.yml using tests/behat/example.local.yml.
 Do you want (re)generate local Behat config in tests/behat/local.yml? (y/n) n
[warning] project.local.uri in blt.yml does not match local.extensions.Behat\MinkExtension.base_url in local.yml.
[warning] project.local.uri = https://naswa.lndo.site
[warning] local.extensions.Behat\MinkExtension.base_url =
[error]  Behat is not configured properly. Please run `blt doctor` to diagnose the issue. 
```

**Comment by lpeabody** [comment]
@brooke-heaton the prompt to rewrite local.yml was answered with 'n' rather than 'y', which would stop it from regenerating local.yml with the correct local site host. I still think it's silly every test is expected to go through the same local.yml rewrite... just seems like an unnecessary hurdle for projects where the hostname is consistent between all development environments.

**Comment by brooke-heaton** [comment]
@lpeabody it's not trying to write a local site hosts, it's trying to totally write a new `local.yml` which OF COURSE I do not want. Does that make sense?

**Comment by brooke-heaton** [comment]
The fact that we can't use multiple Behat profiles in a multisite is insulting and absurd. I'm abandoning BLT because of the lack of assistance here.

**Comment by brooke-heaton** [comment]
Ok, so, I've narrowed down the proper configuration. Ideally this should be documented somewhere. Note that this comments does not work on my end and I've never seen it happen: https://github.com/acquia/blt/issues/2860#issuecomment-480052280

To use a different profile for each multisite, define the following keys in your `/docroot/sites/site1/blt.yml` file: `behat.config` and `behat.profile`. Then ensure your `behat.config` is a path to a functioning Behat config file at `tests/behat`.

Example excerpt from `site1/blt.yml`
```
behat:
  tags: site1
  profile: site1
  config: /app/tests/behat/site1.behat.yml
  suites:
    default:
      paths:
        # Set features to repo root so that .feature files belonging to contrib
        # modules, themes, and profiles can be discovered.
        features: /app/tests/behat/features/site1
```

Example `tests/begat/site1.behat.yml`
```
imports:
  - behat.yml

site1:
  suites:
    default:
      paths:
        # Set features to repo root so that .feature files belonging to contrib
        # modules, themes, and profiles can be discovered.
        features: /app
        bootstrap: /app/tests/behat/features/bootstrap
      contexts:
        - Drupal\FeatureContext:
          parameters:
            environment:
              # absolute path to local directory to store screenshots - do not include trailing slash
              screenshot_dir: ${reports.localDir}
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
    Behat\MinkExtension:
      browser_name: chrome
      javascript_session: default
      # configure the base url for your site
      base_url: https://local.site1.com
      # set default command for "Show last response" step.
      show_cmd: "open %s"
      # use the following lines to disable SSL authentication for goutte.
      # goutte:
      #   guzzle_parameters:
      #     redirect.disable: true
      #     ssl.certificate_authority: system
      #     curl.options:
      #       CURLOPT_SSL_VERIFYPEER: false
      #       CURLOPT_SSL_VERIFYHOST: false
      #       CURLOPT_CERTINFO: false
      #       CURLOPT_TIMEOUT: 120
      selenium2:
        wd_host: ${behat.selenium.url}
        browser: chrome
      sessions:
        default:
          chrome:
            api_url: "http://localhost:9222"
    Drupal\DrupalExtension:
      drupal:
        # This must be an absolute path.
        drupal_root: /app/docroot
      drush:
        alias: '@site1.local'
```
