### ISSUE TITLE
Drush alias variable defenision

### ISSUE THREAD

**Issue by arunavak111** [acquia/blt#2885]
When we check following file blt/scripts/travis/run_tests we can see that it using a drush alias variable `${drush.aliases.ci}`. Where this variable is actually defined. I could not find this variable in `https://docs.travis-ci.com/user/environment-variables`.

**Comment by ba66e77** [comment]
That's from the config in blt.yml, like you can see in the [template file](https://github.com/acquia/blt/blob/9.x/template/blt/blt.yml).

Excerpted:
```
drush:
  # You can set custom project aliases in drush/sites/*.site.yml.
  aliases:
    ....
    # The drush alias against which all ci commands are run.
    ci: 'self'
```
