### ISSUE TITLE
Allow targets to be disabled in project.yml

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#290]
```
# Control which targets are run by the *:build:validate:test processes. You may
# still execute any target individually.
targets:
  frontend:
    build: true
  tests:
    behat: true
    phpunit: true
    security-updates: true
  validate:
    composer: true
    lint: true
    phpcs: true
    twig: true
```

**Comment by grasmash** [comment]
Perhaps we should nest under *:all keys to make impact more clear?

```
# Control which targets are run by the *:build:validate:test processes. You may
# still execute any target individually.
targets:
  frontend:all:
    build: true
  setup:
    behat: true
    drupal:install: true
    config-import: true
    git-hooks: true
  tests:all:
    behat: true
    phpunit: true
    security-updates: true
  validate:all:
    composer: true
    lint: true
    phpcs: true
    twig: true
```
