### ISSUE TITLE
BLT 9 and ACSF - drupal:sync failing due to improperly configured drush alias in blt.yml

### ISSUE THREAD

**Issue by KBeltz** [acquia/blt#2925]
My system information:
* Operating system type: macOS
* Operating system version: 10.13.5 
* BLT version: 9.1.0

Output of `blt doctor`:
```
+---------------------------+----------------------------------------------------------+
| Property                  | Value                                                    |
+---------------------------+----------------------------------------------------------+
| %paths.%root              | /var/www/creighton/docroot                               |
| %paths.%site              | sites/default                                            |
| %paths.%modules           | sites/all/modules                                        |
| %paths.%themes            | sites/all/themes                                         |
| %paths.%config-sync       | /var/www/creighton/config/default                        |
| %paths.%files             | sites/default/files                                      |
| %paths.%temp              | /tmp                                                     |
| %paths.%private           | /var/www/creighton/files-private                         |
| admin-theme               | cu8                                                      |
| alias-searchpaths.0       | /home/vagrant/.drush/sites                               |
| alias-searchpaths.1       | /var/www/creighton/drush/sites                           |
| blt-version               | 9.1.0-alpha1                                             |
| bootstrap                 | Successful                                               |
| composer-version          | Composer version 1.6.5 2018-05-04 11:44:59               |
| config-sync               | /var/www/creighton/config/default                        |
| db-driver                 | mysql                                                    |
| db-hostname               | localhost                                                |
| db-name                   | drupal                                                   |
| db-password               | drupal                                                   |
| db-port                   | 3306                                                     |
| db-status                 | Connected                                                |
| db-username               | drupal                                                   |
| drupal-settings-file      | sites/default/settings.php                               |
| drupal-version            | 8.5.4                                                    |
| drush-alias-files.0       | /home/vagrant/.drush/sites/creighton.site.yml            |
| drush-alias-files.1       | /var/www/creighton/drush/sites/01dev.site.yml            |
| drush-alias-files.2       | /var/www/creighton/drush/sites/01devup.site.yml          |
| drush-alias-files.3       | /var/www/creighton/drush/sites/01live.site.yml           |
| drush-alias-files.4       | /var/www/creighton/drush/sites/01test.site.yml           |
| drush-alias-files.5       | /var/www/creighton/drush/sites/01testup.site.yml         |
| drush-alias-files.6       | /var/www/creighton/drush/sites/01update.site.yml         |
| drush-alias-files.7       | /var/www/creighton/drush/sites/creighton.site.yml        |
| drush-conf.0              | /home/vagrant/.drush/drush.yml                           |
| drush-conf.1              | /var/www/creighton/vendor/drush/drush/drush.yml          |
| drush-conf.2              | /var/www/creighton/drush/drush.yml                       |
| drush-conf.3              | /var/www/creighton/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/creighton/vendor/bin/drush                      |
| drush-temp                | /tmp                                                     |
| drush-version             | 9.3.0                                                    |
| files                     | sites/default/files                                      |
| install-profile           | creighton                                                |
| modules                   | sites/all/modules                                        |
| php-bin                   | /usr/bin/php7.1                                          |
| php-conf.0                | /etc/php/7.1/cli/php.ini                                 |
| php-os                    | Linux                                                    |
| private                   | /var/www/creighton/files-private                         |
| root                      | /var/www/creighton/docroot                               |
| site                      | sites/default                                            |
| stacks.drupal-vm.inited   | true                                                     |
| stacks.dev-desktop.inited | false                                                    |
| temp                      | /tmp                                                     |
| theme                     | cu2017                                                   |
| themes                    | sites/all/themes                                         |
| uri                       | http://local.creighton.com                               |
+---------------------------+----------------------------------------------------------+
+--------------------------------------+-----------------------------------------------------------+
| Check                                | Problem                                                   |
+--------------------------------------+-----------------------------------------------------------+
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root. |
+--------------------------------------+-----------------------------------------------------------+
```

When I run this command:
```
blt drupal:sync --site=shaneandcolinshareabirthday.dev-creighton.acsitefactory.com -vvv 
```

I get the following output:
```
> source:build:composer
[Exec] Running export COMPOSER_EXIT_ON_PATCH_FAILURE=1; composer install --ansi --no-interaction in /var/www/creighton
Warning: The value for extra.installer-paths in composer.json differs from BLT's recommended values.
See /var/www/creighton/vendor/acquia/blt/template/composer.json
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
[Exec] Done in 3.064s
> blt:init:settings
[debug] Switching site context to default.
[Filesystem\FilesystemStack] _chmod ["/var/www/creighton/docroot/sites/default",511]
[Filesystem\FilesystemStack] _chmod ["/var/www/creighton/docroot/sites/default/settings.php",511]
 2/2 [============================] 100% < 1 sec/< 1 sec 10.0 MiB
[File\Write] Writing to /var/www/creighton/docroot/sites/default/settings.php.
[Filesystem\FilesystemStack] _chmod ["/var/www/creighton/docroot/sites/default/settings.php",420]
 1/1 [============================] 100% < 1 sec/< 1 sec 10.0 MiB
[debug] Switching site context to shaneandcolinshareabirthday.dev-creighton.acsitefactory.com.
> drupal:sync:db
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/creighton/vendor/bin/drush cache-clear drush --uri=shaneandcolinshareabirthday.dev-creighton.acsitefactory.com --no-interaction --ansi &&
 /var/www/creighton/vendor/bin/drush sql-drop --uri=shaneandcolinshareabirthday.dev-creighton.acsitefactory.com --no-interaction --ansi &&
 /var/www/creighton/vendor/bin/drush sql-sync @creighton.test @self --target-dump=/tmp/tmp.target.sql.gz --structure-tables-key=lightweight --create-db --uri=shaneandcolinshareabirthday.dev-creighton.acsitefactory.com --no-interaction --ansi &&
 /var/www/creighton/vendor/bin/drush sql-sanitize --uri=shaneandcolinshareabirthday.dev-creighton.acsitefactory.com --no-interaction --ansi &&
 /var/www/creighton/vendor/bin/drush cr --uri=shaneandcolinshareabirthday.dev-creighton.acsitefactory.com --no-interaction --ansi &&
 /var/www/creighton/vendor/bin/drush sqlq "TRUNCATE cache_entity" --uri=shaneandcolinshareabirthday.dev-creighton.acsitefactory.com --no-interaction --ansi in /var/www/creighton/docroot
 [notice] Missing database table: key_value
 [success] 'drush' cache was cleared.
 [error]  Error: no alias record could be found for source @creighton.test 
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 1.143s
[error]   
[error]  Command `drupal:sync:db ` exited with code 1. 
4.906s total time elapsed.
```

And I expected this to happen:
Honestly, it makes sense that this is failing. I don't have an @creighton.test alias. The output of `drush sa` is:

```
'@01dev.dev':
  host: creighton01dev.ssh.enterprise-g1.acquia-sites.com
  options:
    ac-env: 01dev
    ac-realm: enterprise-g1
    ac-site: creighton
  paths:
    drush-script: drush9
  root: /var/www/html/creighton.01dev/docroot
  uri: creighton01dev.enterprise-g1.acquia-sites.com
  user: creighton.01dev
'@01dev.livedev':
  options:
    parent: '@creighton.01dev'
  root: /mnt/gfs/creighton.01dev/livedev/docroot
'@01devup.dev':
  host: creighton01devup.ssh.enterprise-g1.acquia-sites.com
  options:
    ac-env: 01devup
    ac-realm: enterprise-g1
    ac-site: creighton
  paths:
    drush-script: drush9
  root: /var/www/html/creighton.01devup/docroot
  uri: creighton01devup.enterprise-g1.acquia-sites.com
  user: creighton.01devup
'@01devup.livedev':
  options:
    parent: '@creighton.01devup'
  root: /mnt/gfs/creighton.01devup/livedev/docroot
'@01live.dev':
  host: creighton01live.ssh.enterprise-g1.acquia-sites.com
  options:
    ac-env: 01live
    ac-realm: enterprise-g1
    ac-site: creighton
  paths:
    drush-script: drush9
  root: /var/www/html/creighton.01live/docroot
  uri: creighton01live.enterprise-g1.acquia-sites.com
  user: creighton.01live
'@01live.livedev':
  options:
    parent: '@creighton.01live'
  root: /mnt/gfs/creighton.01live/livedev/docroot
'@01test.dev':
  host: creighton01test.ssh.enterprise-g1.acquia-sites.com
  options:
    ac-env: 01test
    ac-realm: enterprise-g1
    ac-site: creighton
  paths:
    drush-script: drush9
  root: /var/www/html/creighton.01test/docroot
  uri: creighton01test.enterprise-g1.acquia-sites.com
  user: creighton.01test
'@01test.livedev':
  options:
    parent: '@creighton.01test'
  root: /mnt/gfs/creighton.01test/livedev/docroot
'@01testup.dev':
  host: creighton01testup.ssh.enterprise-g1.acquia-sites.com
  options:
    ac-env: 01testup
    ac-realm: enterprise-g1
    ac-site: creighton
  paths:
    drush-script: drush9
  root: /var/www/html/creighton.01testup/docroot
  uri: creighton01testup.enterprise-g1.acquia-sites.com
  user: creighton.01testup
'@01testup.livedev':
  options:
    parent: '@creighton.01testup'
  root: /mnt/gfs/creighton.01testup/livedev/docroot
'@01update.dev':
  host: creighton01update.ssh.enterprise-g1.acquia-sites.com
  options:
    ac-env: 01update
    ac-realm: enterprise-g1
    ac-site: creighton
  paths:
    drush-script: drush9
  root: /var/www/html/creighton.01update/docroot
  uri: creighton01update.enterprise-g1.acquia-sites.com
  user: creighton.01update
'@01update.livedev':
  options:
    parent: '@creighton.01update'
  root: /mnt/gfs/creighton.01update/livedev/docroot
'@creighton.local':
  options: {  }
  root: /var/www/creighton/docroot
  uri: local.creighton.com
'@creighton.www':
  options: {  }
  root: /var/www/creighton/docroot
  uri: www.local.creighton.com
```

Basically, I don't know how I should update `remote: '${project.machine_name}.test'` in blt.yml to call the appropriate aliases.
