### ISSUE TITLE
Documentation/Assistance with Drupal 8 Multisite and CI (Travis)

### ISSUE THREAD

**Issue by brooke-heaton** [acquia/blt#2973]
Sorry if this is not the right avenue, but I'm having difficulty understanding how to run the Travis build process on a multisite. Currently Travis is doing a build and importing configuration only for the `/default` site. I do however have settings in my `blt.yml` file for my multisite and am able to run blt commands such as `blt sync --site=sub_site` and this does work. Are special settings needed in the `.travis.yml` file or in the subsite specific `sites/subsites/blt.yml` file?

**Comment by dpagini** [comment]
Hey Brooke - As far as I've seen, Travis will not auto run anything for you for multisite. What I would suggest is taking that command you mention (`$ blt sync --site=sub_site`) and tacking it on to your `script` section in your `.travis.yml file...
So you would have:
```yml
install:
  - source ${BLT_DIR}/scripts/travis/setup_environment
  - source ${BLT_DIR}/scripts/travis/setup_project

script:
  - source ${BLT_DIR}/scripts/travis/run_tests
  - blt sync --site=sub_site1
  - blt sync --site=sub_site2
```

...or you could look into the `$ blt sync:all` command instead of the two separate ones there.

So obviously the `run_test` command is building your default site, and the other two commands are syncing from a database... so slight differences there. But anyways, I think that should get you closer...?
