### ISSUE TITLE
drush.yml config paths are wrong

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#3010]
The config paths in [template/drush/drush.yml](https://github.com/acquia/blt/blob/9.1.1/template/drush/drush.yml) are relative to the file, but Drush interprets them relative to the current working directory; so the referenced files are only found and interpreted if you happen to be invoking Drush from the `drush/` directory. Since I almost always work from either the repository root or within the VM, the below change mostly covers the bases for me; but it's just a bandaid. Anyone have any thoughts on a more scalable solution?

```diff
--- a/drush/drush.yml
+++ b/drush/drush.yml
@@ -5,9 +5,11 @@ drush:
   paths:
     config:
       # Load a drush.yml configuration file from the current working directory.
-      - ../docroot/sites/default/local.drush.yml
+      - docroot/sites/default/local.drush.yml
+      - /var/www/myproject/docroot/sites/default/local.drush.yml
       # Allow local global config overrides.
-      - local.drush.yml
+      - drush/local.drush.yml
+      - /var/www/myproject/drush/local.drush.yml
     include:
       - '${env.home}/.drush'
       - /usr/share/drush/commands
```

**Comment by lcatlett** [comment]
I have never had this issue with the BLT default drush config so I wonder if it is a drush bug. 

It is my understanding that your default project `drush.yml` should go in blt's repo.root/drush directory, then you can include individual paths like you said to the `local.drush.yml` config for each multisite in the config section either hard coded or through an environment variable via env subtitution such as ${env.name}. If I set a `SITE` environment variable in the shell, the drush.yml in the project's drush directory could use the value of SITE through something like the below:

````
# This file defines drush configuration that applies to drush commands
# for the entire application. For site-specific settings, like URI, use
# ../docroot/sites/[site]/drush.yml
drush:
  paths:
    config:
      # Load a drush.yml configuration file from the current working directory.
     - ../docroot/sites/default/local.drush.yml
      # Allow local global config overrides.
      - local.drush.yml
      - '../docroot/sites/${env.site}/local.drush.yml'
    include:
      - '${env.home}/.drush'
      - /usr/share/drush/command
```
