### ISSUE TITLE
Running Update Hooks on CDE fires Drupal Install instead of Db-sync/update

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#3022]
Am using Acquia Pipelines + Acquia CDE.  It looks like there is an assumption in the blt/cloudhooks command:

https://github.com/acquia/blt/blob/9.x/src/Robo/Commands/Artifact/AcHooksCommand.php#L137
```
public function updateOdeSites() {
    $this->invokeCommand('artifact:install:drupal');
  }
```
Its assuming that you will always want to run Drupal install, instead of 
`$this->invokeCommand('artifact:update:drupal:all-sites');`

If you are leveraging the new DB-sync functionality in pipelines/ode this is problematic:

```
version: 1.2.0
services:
  - mysql
  - php:
      version: 7.1

cde-databases:
  - mydb

  post-deploy:
    steps:
        - deploy:
           type: script
           script:
             - pipelines-deploy
             - pipelines-sync-dbs mydb
```

Probably need to make this logic configurable via blt.yml.  Something to the effect of `ODE-strategy`
sync or install
