### ISSUE TITLE
Ability to run multiple behat suites

### ISSUE THREAD

**Issue by justclint** [acquia/blt#3275]
My system information:
* Operating system type: OSX
* Operating system version: 10.13.6
* BLT version: 9.2.1

Output of `blt doctor`:
```
| Property                  | Value                                                  |
+---------------------------+--------------------------------------------------------+
| %paths.%root              | /var/www/{project}/docroot                               |
| %paths.%site              | sites/default                                          |
| %paths.%modules           | sites/all/modules                                      |
| %paths.%themes            | sites/all/themes                                       |
| %paths.%config-sync       | /var/www/{project}/config/default                        |
| %paths.%files             | sites/default/files                                    |
| %paths.%temp              | /tmp                                                   |
| %paths.%private           | /var/www/{project}/files-private                         |
| admin-theme               | seven                                                  |
| alias-searchpaths.0       | /var/www/{project}/drush/sites                           |
| blt-version               | 9.2.1                                                  |
| bootstrap                 | Successful                                             |
| composer-version          | Composer version 1.7.3 2018-11-01 10:05:06             |
| config-sync               | /var/www/{project}/config/default                        |
| db-driver                 | mysql                                                  |
| db-hostname               | localhost                                              |
| db-name                   | drupal                                                 |
| db-password               | drupal                                                 |
| db-port                   | 3306                                                   |
| db-status                 | Connected                                              |
| db-username               | drupal                                                 |
| drupal-settings-file      | sites/default/settings.php                             |
| drupal-version            | 8.6.2                                                  |
| drush-alias-files.0       | /var/www/{project}/drush/sites/example.acsf.site.yml     |
| drush-alias-files.1       | /var/www/{project}/drush/sites/example.local.site.yml    |
| drush-alias-files.2       | /var/www/{project}/drush/sites/legacy.site.yml           |
| drush-alias-files.3       | /var/www/{project}/drush/sites/{project}-dev.site.yml      |
| drush-alias-files.4       | /var/www/{project}/drush/sites/{project}-prod.site.yml     |
| drush-alias-files.5       | /var/www/{project}/drush/sites/{project}-qa.site.yml       |
| drush-alias-files.6       | /var/www/{project}/drush/sites/{project}-ra.site.yml       |
| drush-alias-files.7       | /var/www/{project}/drush/sites/{project}-test.site.yml     |
| drush-alias-files.8       | /var/www/{project}/drush/sites/{project}.site.yml          |
| drush-cache-directory     | /home/vagrant/.drush/cache                             |
| drush-conf.0              | /var/www/{project}/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/{project}/drush/drush.yml                       |
| drush-conf.2              | /var/www/{project}/docroot/drush                         |
| drush-conf.3              | /var/www/{project}/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/{project}/vendor/bin/drush                      |
| drush-temp                | /tmp                                                   |
| drush-version             | 9.5.2                                                  |
| files                     | sites/default/files                                    |
| install-profile           | lightning                                              |
| modules                   | sites/all/modules                                      |
| php-bin                   | /usr/bin/php7.1                                        |
| php-conf.0                | /etc/php/7.1/cli/php.ini                               |
| php-os                    | Linux                                                  |
| private                   | /var/www/{project}/files-private                         |
| root                      | /var/www/{project}/docroot                               |
| site                      | sites/default                                          |
| stacks.drupal-vm.inited   | true                                                   |
| stacks.dev-desktop.inited | false                                                  |
| temp                      | /tmp                                                   |
| theme                     | bootstrap_padi                                         |
| themes                    | sites/all/themes                                       |
| uri                       | http://local.{project}.com                               |
+---------------------------+--------------------------------------------------------+
+--------------------------------------+--------------------+
| Check                                | Problem            |
+--------------------------------------+--------------------+
| NodeCheck:checkNodeVersionFileExists | .nvmrc file exists |
```

When I run this command:
```
blt tests:behat:run
```

I get the following output:
```
Behat only runs through the local.yml config file. Adding addtional suites to this config file does not work.
```
And I expected this to happen:

We've just started using the domain_access module and setup some additional domains. Im trying to get the BLT tests:behat command to run multiple suites or config files since each domain will have a different behat base_url.

Ive created another local config as "local-sample.yml" with the a different base_url and a suite called "local-sample" which I can run with:

`blt tests:behat:run -D behat.config='tests/behat/local-sample.yml' -D behat.profile='local-sample'`

The tests run successfully on the new base_url but Id like to automate this.

Is there a way to add additional behat profiles or suites to run on `blt tests:behat:run`?

**Comment by timwood** [comment]
Related to #2860

**Comment by brooke-heaton** [comment]
Any documentation on running Behat in a multisite BLT setup would be appreciated.

**Comment by brooke-heaton** [comment]
Related to #3445

**Comment by danepowell** [comment]
BLT isn't strongly opinionated about how to organize Behat tests in multisite environments because there's such a wide variety of use cases. Not every site needs testing in every project, some prefer to group tests by site profile, others share tests across sites, others have completely unique tests per site, etc... I don't see one solution that fits all projects, so instead BLT tries to provide as much flexibility as possible via configuration options.

Based on what you've described, I don't see why you'd need to modify BLT's template Behat yml files or directory structure at all. Couldn't you keep all of your tests in BLT's standard directories, tag the tests you want to run on each site (e.g. `@foo`, `@bar`), and then define the tags you want to run for each site in the respective blt.yml?

For instance, `docroot/sites/foo/blt.yml` would have the following contents:
```yml
behat:
  tags: foo
```

I just tested this and it worked great.

**Comment by danepowell** [comment]
I think the next step for this will be a documentation fix, which we'll handle in #3690

**Comment by brooke-heaton** [comment]
Hm, I'm rather confused about this as well. Haven't really seen any new updates/documentation for multisites and Behat.

I have two separate Behat profiles for each multisite, which makes sense, so that I can run different test suites and use different base_urls, of course.

I can run this command and everything works perfectly:
`lando behat --format pretty /app/tests/behat --colors --no-interaction --stop-on-failure --strict --config /app/tests/behat/local.yml --profile naswa --tags naswa -v`

Translating that into BLT, this _should_ become

`blt tests:behat:run --site=naswa -D behat.config='tests/behat/local.yml' -D behat.profile='naswa'`

However that simply spits out an error, which is odd, because I'm simply overriding the profile with a perfectly fine profile. 
```
[warning] project.local.uri in blt.yml does not match local.extensions.Behat\MinkExtension.base_url in local.yml.
[warning] project.local.uri = https://naswa.lndo.site
[warning] local.extensions.Behat\MinkExtension.base_url =
[warning] Behat is not configured properly.
BLT can (re)generate tests/behat/local.yml using tests/behat/example.local.yml.
```

huh?

**Comment by brooke-heaton** [comment]
For good measuring, here are the full contents of my current 'tests/behat/local.yml' file

```
naswa:
  suites:
    default:
      paths:
        # Set features to repo root so that .feature files belonging to contrib
        # modules, themes, and profiles can be discovered.
        features: /app
        bootstrap: /app/tests/behat/features/bootstrap
      contexts:
        - Drupal\FeatureContext:
          parameters:
            environment:
              # absolute path to local directory to store screenshots - do not include trailing slash
              screenshot_dir: ${reports.localDir}
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
    Behat\MinkExtension:
      browser_name: chrome
      javascript_session: default
      # configure the base url for your site
      base_url: https://naswa.lndo.site
      # set default command for "Show last response" step.
      show_cmd: "open %s"
      # use the following lines to disable SSL authentication for goutte.
      # goutte:
      #   guzzle_parameters:
      #     redirect.disable: true
      #     ssl.certificate_authority: system
      #     curl.options:
      #       CURLOPT_SSL_VERIFYPEER: false
      #       CURLOPT_SSL_VERIFYHOST: false
      #       CURLOPT_CERTINFO: false
      #       CURLOPT_TIMEOUT: 120
      selenium2:
        wd_host: ${behat.selenium.url}
        browser: chrome
      sessions:
        default:
          chrome:
            api_url: "http://localhost:9222"
    Drupal\DrupalExtension:
      drupal:
        # This must be an absolute path.
        drupal_root: /app/docroot
      drush:
        alias: '@naswa.local'
```
