### ISSUE TITLE
Custom PHPUnit execution broke with #3351.

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#3752]
**Describe the bug**
At some point over the last few months, our custom PHPUnit tests stopped being executed.

**To Reproduce**
1. Place a test in a BLT folder such as `example/test/MyCustomTest.php`
1. Configure your BLT configuration to run the test, so set the following properties in `blt/blt.yml`...
```
tests:
  phpunit:
    -
      path: '${repo.root}/example/test'
      config: null
```
3. Run `$ blt tests:phpunit:run`

**Expected behavior**
My unit test should run successfully.

**System information**
* Operating system type: Ubuntu
* Operating system version: 16.x
* BLT version: 10.2

**Additional context**
I believe this was introduced for me [here](https://github.com/acquia/blt/pull/3351/files#diff-5e11eea581463b07c21f286ee9903bf3R103) when BLT changed the path to be the directory instead of the argument to `phpunit` binary.

Not sure if there was a reason for this change, but wondering if changing this back would fix this issue?

**Comment by greylabel** [comment]
I don't think we want to revert that for few reasons, mostly significant performance degradations.

Can you try:
```
tests:
  phpunit:
    -
      directory: '${repo.root}/example/test'
      path: '${repo.root}/example/test'
      config: null
```

See: https://github.com/acquia/blt/blob/10.x/tests/phpunit/src/TestPhpUnitCommandTest.php for an example.

If it fails, can you provide more complete error output showing the command sequence as it was executed by BLT?
