### ISSUE TITLE
BLT 9 fails on Drupal/Core 8.7.x due to a required patch

### ISSUE THREAD

**Issue by loopy3025** [acquia/blt#3848]
I am trying to incrementally upgrade BLT from 8 to 9 then 10. On the 8-9 step, It's trying to install /files/issues/2788777-3-146.patch (Allow a site-specific profile to be installed from existing config)

Which doesn't apply to the version of Drupal it's trying to install (8.7.7). Ostensibly, BLT 9.2.8 is supposed to be compatible with drupal core ^8.7.x

So, I added this to my composer file:
```

        "composer-exit-on-patch-failure": false,
        "patches-ignore": {
            "drupal/core": {
                "Allow a site-specific profile to be installed from existing config": "https://www.drupal.org/files/issues/2788777-3-146.patch"
            }
``` 
Which does work when building locally, but when I try to push it through pipelines, it throws an error.  I tried adding the variable declaration to my acquia-pipelines.yml file, but that seems not to have worked either.

```
variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    BLT_DIR: $SOURCE_DIR/vendor/acquia/blt
    COMPOSER_EXIT_ON_PATCH_FAILURE: 0
```
and
```
        - setup-app:
            type: script
            script:
              - COMPOSER_EXIT_ON_PATCH_FAILURE=0
              - source ${BLT_DIR}/scripts/pipelines/setup_app
```
How can I set the exit on patch to false when building with BLT?
