### ISSUE TITLE
Compiling front-end assets in multiple themes

### ISSUE THREAD

**Issue by gosia-mlynarczyk** [acquia/blt#3852]
Hi,

I'm brand new to BLT and have a question about building front-end assets. I had a look at the docs (https://docs.acquia.com/blt/developer/frontend/#build). This works for me when compiling front-end assets in a theme:
```
command-hooks:
 frontend-assets:
   dir: ${docroot}/themes/custom/mytheme
   command: 'npm run build'
```
My question is, is there a way to compile front-end assets in multiple themes on the same site? Something like:
```
command-hooks:
 frontend-assets:
   - dir: ${docroot}/themes/custom/mytheme1
     command: 'npm run build'
   - dir: ${docroot}/themes/custom/mytheme2
     command: 'gulp build'
```
The code above didn't work for me. When I ran `blt source:build:frontend` I got the following output:
```
> source:build:frontend-reqs
> source:build:frontend-assets
```

Is `frontend-assets` command expecting a single `dir` and `command`, or is my syntax wrong?

Thanks!
