### ISSUE TITLE
Travis fails to push artifact

### ISSUE THREAD

**Issue by richardbporter** [acquia/blt#4000]
**Describe the bug**
We're getting this error when Travis attempts to push an artifact to a remote:
```
blt artifact:deploy --commit-msg "Automated commit by Travis CI for Build ${TRAVIS_BUILD_ID}" --branch "${TRAVIS_BRANCH}-build" --no-interaction --verbose
Commit message is set to Automated commit by Travis CI for Build 147442076.
Branch is set to develop-build.
Preparing artifact directory...
[error]  Failed to remove directory "/home/travis/build/my/project/deploy/.git": rmdir(/home/travis/build/my/project/deploy/.git): Directory not empty. 
3.093s total time elapsed.
Script failed with status 1
```

**To Reproduce**
I can't reproduce this locally. It seems to be a permissions issue on Travis related to the deploy directory created during the `simulate_deploy` script. Removing or commenting out the `- source ${BLT_DIR}/scripts/travis/simulate_deploy` line in the `.travis.yml` fixes the issue. I would assume because the deploy directory is not created then.

**Expected behavior**
I would expect the `deploy_branch` script to be able to clean up after the `simulate_deploy` script. Perhaps there are different user/permissions in play during the deploy stage of the job.

Abridged .travis.yml file:
```
language: php
dist: xenial

php: "7.2"

env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

services:
- mysql

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install
  - source ${BLT_DIR}/scripts/travis/exit_early
  - source ${BLT_DIR}/scripts/travis/setup_environment
  - source ${BLT_DIR}/scripts/travis/setup_project

script:
  - ./vendor/bin/blt setup --define drush.alias='${drush.aliases.ci}' --no-interaction --ansi --verbose
  - source ${BLT_DIR}/scripts/travis/run_tests
  - source ${BLT_DIR}/scripts/travis/simulate_deploy

deploy:
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: develop
       php: 7.2
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: master
       php: 7.2
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_tag"
     skip_cleanup: true
     on:
       tags: true
       php: 7.2

```

**System information**
* Operating system type: Linux
* Operating system version: Ubuntu 16.04.6 LTS
* BLT version: 11.1.0
