### ISSUE TITLE
Travis CI deployment fails due to "uncommitted" travis_wait* log file

### ISSUE THREAD

**Issue by UTCGilligan** [acquia/blt#4012]
**I want to...**
Deploy from Travis CI an updated Github private codebase with Drupal 8.8 and BLT 11 (recently updated from D8.7.1/BLT10.7.2).

**I can...**
Deploy direct from local to Acquia Cloud Enterprise via `ads deploy`). Site also builds locally via blt setup, and has been successfully deployed to ACE Stage environment by tag and tested with refreshed prod database and files. "IT JUST WORKS!"

Github/Travis deploy fails.

I have also tried deleting the Travis log and restarting the build, and triggered a new build via a minimal code commit/PR/merge in Github.

**It's not working because...**
Entire Travis CI build process passes, but fails at deployment.

```
blt artifact:deploy --commit-msg "Automated commit by Travis CI for Build ${TRAVIS_BUILD_ID}" --branch "${TRAVIS_BRANCH}-build" --no-interaction --verbose
1145 ?? travis_wait_2130.log
1146 [error]  There are uncommitted changes on the source repository (listed above). Commit, stash, or remove these changes before deploying, or use the --ignore-dirty flag. Additional guidance is available at https://support.acquia.com/hc/en-us/articles/360035204013-Dirty-BLT-source-directory-prevents-deploys.
1147 For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
1148 0.238s total time elapsed.
1149
1150 Script failed with status 1
1151 failed to deploy
```

**Project's travis.yml:**
```
language: php
dist: xenial

php:
  - 7.3

matrix:
  fast_finish: true

env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
    - BUILD_DIR=$TRAVIS_BUILD_DIR

jdk:
  - oraclejdk8

cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.npm"
    - "$HOME/.nvm"
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - ".rules"
    # Cache front end dependencies to dramatically improve build time.
    - "docroot/themes/custom/xxx_st/node_modules"
    - "docroot/themes/custom/xxx_st/bower_components"
    - "docroot/themes/custom/xxx/node_modules"
    - "docroot/themes/custom/xxx/bower_components"

services:
- mysql
- xvfb

addons:
  ssh_known_hosts:
  # xxx app
  #  - svn-redacted.devcloud.hosting.acquia.com
  # xxx app
    - svn-redacted.prod.hosting.acquia.com
    - staging-redacted.prod.hosting.acquia.com
  chrome: stable

# @see https://docs.travis-ci.com/user/notifications
# notifications:
#   - hipchat: [api token]@[room id or name]
#   - slack: '<account>:<token>#[channel]'

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate --no-check-all --ansi
  - composer install
  # Exit build early if only documentation was changed in a Pull Request.
  - source ${BLT_DIR}/scripts/travis/exit_early

install:
  - source ${BLT_DIR}/scripts/travis/setup_environment
  - source ${BLT_DIR}/scripts/travis/setup_project

script:
  # Uncomment these lines to test database updates using live content.
  # - blt drupal:sync:default:site
   - source ${BLT_DIR}/scripts/travis/run_tests
   - source ${BLT_DIR}/scripts/travis/simulate_deploy

deploy:
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: develop
       php: 7.3
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: master
       php: 7.3
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_tag"
     skip_cleanup: true
     on:
       tags: true
       php: 7.3
```

**System information**
* Operating system type: Travis CI Ubuntu
* Operating system version: N/A
* BLT version: 11.2.0
