### ISSUE TITLE
Cann't seem to disable phpunit

### ISSUE THREAD

**Issue by sodacrackers** [acquia/blt#4018]
**Describe the bug**
We have set disable-targets in `./blt/blt.yml` but `$TRAVIS_BUILD_DIR/vendor/bin/phpunit` seems to keep getting run. It's called without parameters and so breaks the travis build.

We'd like to disable BLT tests, so travis-ci _environments_ can be used, and one environment can will build an artifact quickly and the second can run lengthy tests.

For some reason `$TRAVIS_BUILD_DIR/vendor/bin/phpunit` keeps getting called, killing the build.

**To Reproduce**
We inspected  https://github.com/acquia/blt/blob/11.x/config/build.yml, and also copied entries from the travis build log to disable most tests in ./blt/blt.yml: 
```
disable-targets:
  validate:
    twig: true
  tests:
    behat: { all: true, run: true }
    composer: { validate: true }
    deprecated: { modules: true, themes: true }
    drupal: { drupal-tests: true, phpunit: true }
    frontend: { run: true }
    php: { lint: true }
    phpcs: { sniff: { all: true } }
    phpunit: { all: true, run: true }
    phpstan: { all: true, run: true }
    security: { check: { updates: true } }
    twig: { lint: { all: true } }
    yaml: { lint: { all: true } }
```

But travis finishes with these lines:
```
before_install.1
0.03s$ phpenv config-rm xdebug.ini
before_install.2
0.21s$ composer validate --no-check-all --ansi
before_install.3
28.39s$ composer install
before_install.4
0.01s$ source ${BLT_DIR}/scripts/travis/exit_early
install.1
11.47s$ source ${UWM_BLT}/custom-scripts/travis/setup_environment
install.2
0.00s$ source ${UWM_BLT}/custom-scripts/travis/setup_project
$ $TRAVIS_BUILD_DIR/vendor/bin/phpunit
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.
Usage: phpunit [options] UnitTest [UnitTest.php]
       phpunit [options] <directory>
Code Coverage Options:
  --coverage-clover <file>    Generate code coverage report in Clover XML format
  --coverage-crap4j <file>    Generate code coverage report in Crap4J XML format
  --coverage-html <dir>       Generate code coverage report in HTML format
  --coverage-php <file>       Export PHP_CodeCoverage object to file
  --coverage-text=<file>      Generate code coverage report in text format
```

**Expected behavior**
I can add a blt command to the build script without `$ $TRAVIS_BUILD_DIR/vendor/bin/phpunit`  getting called. 

**System information**
Built config: https://travis-ci.org/uwmweb/uwmcms/jobs/652329567/config
blt -V    BLT 11.2.0
