### ISSUE TITLE
ignoreDirty implementation?

### ISSUE THREAD

**Issue by ejanus** [acquia/blt#4111]
**I want to...**
After upgrading from BLT 10 to BLT 11 on my local env and attempting to deploy. 

I ran into an issue where I need to override the travis build/tag deploy scripts in my own projects to use `--ignore-dirty` flag and properly run at the end of the build without incident. 

I realize I need to do my DD and solve for why I have dirty builds but, I need to get this deployed for now. 

**It's not working because...**
Not sure, I get error 127 at the end of the build digest.

**Steps I've taken**

I created a `/scripts/travis` folder, copying the `deploy_branch` and `deploy_tag` from the vendor folder. I modified the deploy commands on each of the copied scripts to be as follows (no other modification was made to the copies):

**deploy_branch**
```
blt artifact:deploy --commit-msg "Automated commit by Travis CI for Build ${TRAVIS_BUILD_ID}" --branch "${TRAVIS_BRANCH}-build" --ignore-dirty --no-interaction --verbose
```

**deploy_tag**
```
blt artifact:deploy --commit-msg "Automated commit by Travis CI for Build ${TRAVIS_TAG}" --tag "${TRAVIS_TAG}-build" --ignore-dirty --no-interaction --verbose
```

I updated my .travis.yml file to point to these as follows (I think the issue may be here?):
```
sudo: true
language: php
dist: xenial

# Adjust the version of PHP to match your production environment.
# Making this version number greater than the production environment can have unintended consequences
# including a non-functional prod environment.
php:
  - 7.2

matrix:
  fast_finish: true

env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
    - BUILD_DIR=$TRAVIS_BUILD_DIR

jdk:
  - oraclejdk8

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - ".rules"
  # Cache front end dependencies to dramatically improve build time.
  - "docroot/themes/custom/bootstrap_proj/node_modules"
  # - "docroot/themes/custom/mytheme/bower_components"

services:
- mysql
- xvfb

addons:
  ssh_known_hosts:
  - svn-12345.prod.hosting.acquia.com
  chrome: stable

# @see https://docs.travis-ci.com/user/notifications
notifications:
  slack:
    rooms:
    - projww:KJDLKkjdfkjDLKJD#proj-com-eng
    template:
    - "Build: <%{build_url}|#%{build_number}> (%{duration}) / Commit: <%{compare_url}|%{commit}> *%{message}* \n%{author}: %{branch} \n%{commit_message}"
# - hipchat: [api token]@[room id or name]
# - slack: '<account>:<token>#[channel]'

before_script:
  # Additional PHP config
  - phpenv config-add travis.php.ini

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate --no-check-all --ansi
  - composer install
  - chmod -v 600 services/oauth/public.key
  # Exit build early if only documentation was changed in a Pull Request.
  - source ${BLT_DIR}/scripts/travis/exit_early
  # Add .npmrc for Artifactory
  - cp travis.npmrc docroot/themes/custom/bootstrap_proj/.npmrc

install:
  - source ${BLT_DIR}/scripts/travis/setup_environment
  - source ${BLT_DIR}/scripts/travis/setup_project

script:
  # Uncomment these lines to test database updates using live content.
  # - blt drupal:sync:default:site
  - source ${BLT_DIR}/scripts/travis/run_tests

# The version below MUST match the php version indicated at the top of this file, otherwise the artifact won't build.
deploy:
   - provider: script
     script: "${TRAVIS_BUILD_DIR}/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: develop
       php: 7.2
   - provider: script
     script: "${TRAVIS_BUILD_DIR}/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: master
       php: 7.2
   - provider: script
     script: "${TRAVIS_BUILD_DIR}/scripts/travis/deploy_tag"
     skip_cleanup: true
     on:
       tags: true
       php: 7.2

```

**Detailed error output**
```
The command "source ${BLT_DIR}/scripts/travis/run_tests" exited with 0.
cache.2
store build cache
dpl_0
1.23s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
dpl.1
Installing deploy dependencies
Successfully installed dpl-script-1.10.15
1 gem installed
dpl.2
Preparing deploy
dpl.3
Deploying application
Script failed with status 127
failed to deploy
```

**BLT doctor output**
```
+---------------------------+--------------------------------------------------------+
| Property                  | Value                                                  |
+---------------------------+--------------------------------------------------------+
| %paths.%root              | /var/www/projblt/docroot                               |
| %paths.%site              | sites/default                                          |
| %paths.%modules           | sites/all/modules                                      |
| %paths.%themes            | sites/all/themes                                       |
| %paths.%config-sync       | /var/www/projblt/config/default                        |
| %paths.%files             | sites/default/files                                    |
| %paths.%temp              | /tmp                                                   |
| %paths.%private           | /var/www/projblt/files-private                         |
| admin-theme               | seven                                                  |
| alias-searchpaths.0       | /var/www/projblt/drush/sites                           |
| base-profile              |                                                        |
| blt-version               | 11.4.0                                                 |
| bootstrap                 | Successful                                             |
| composer-version          | Composer version 1.10.1 2020-03-13 20:34:27            |
| config-sync               | /var/www/projblt/config/default                        |
| db-driver                 | mysql                                                  |
| db-hostname               | localhost                                              |
| db-name                   | drupal                                                 |
| db-password               | drupal                                                 |
| db-port                   | 3306                                                   |
| db-status                 | Connected                                              |
| db-username               | drupal                                                 |
| drupal-settings-file      | sites/default/settings.php                             |
| drupal-version            | 8.8.4                                                  |
| drush-alias-files.0       | /var/www/projblt/drush/sites/example.acsf.site.yml     |
| drush-alias-files.1       | /var/www/projblt/drush/sites/example.local.site.yml    |
| drush-alias-files.2       | /var/www/projblt/drush/sites/legacy.site.yml           |
| drush-alias-files.3       | /var/www/projblt/drush/sites/projblt-dev.site.yml      |
| drush-alias-files.4       | /var/www/projblt/drush/sites/projblt-prod.site.yml     |
| drush-alias-files.5       | /var/www/projblt/drush/sites/projblt-qa.site.yml       |
| drush-alias-files.6       | /var/www/projblt/drush/sites/projblt-ra.site.yml       |
| drush-alias-files.7       | /var/www/projblt/drush/sites/projblt-test.site.yml     |
| drush-alias-files.8       | /var/www/projblt/drush/sites/projblt.site.yml          |
| drush-cache-directory     | /home/vagrant/.drush/cache                             |
| drush-conf.0              | /var/www/projblt/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/projblt/drush/drush.yml                       |
| drush-conf.2              | /var/www/projblt/docroot/drush                         |
| drush-conf.3              | /var/www/projblt/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/projblt/vendor/drush/drush/drush              |
| drush-temp                | /tmp                                                   |
| drush-version             | 9.7.2                                                  |
| files                     | sites/default/files                                    |
| install-profile           | lightning                                              |
| modules                   | sites/all/modules                                      |
| php-bin                   | /usr/bin/php7.2                                        |
| php-conf.0                | /etc/php/7.2/cli/php.ini                               |
| php-os                    | Linux                                                  |
| private                   | /var/www/projblt/files-private                         |
| root                      | /var/www/projblt/docroot                               |
| site                      | sites/default                                          |
| stacks.drupal-vm.inited   | true                                                   |
| stacks.dev-desktop.inited | false                                                  |
| temp                      | /tmp                                                   |
| theme                     | bootstrap_proj                                         |
| themes                    | sites/all/themes                                       |
| uri                       | http://local.projblt.com                               |
+---------------------------+--------------------------------------------------------+
+----------------------------------------------+--------------------------------------------------------------+
| Check                                        | Problem                                                      |
+----------------------------------------------+--------------------------------------------------------------+
| ComposerCheck:composer.extra.installer-paths | The Composer configuration for extra.installer-paths differs |
|                                              | from BLT's default, recommended values.                      |
|                                              |   Change your configuration to match BLT's defaults in       |
|                                              |                                                              |
|                                              | vendor/acquia/blt/subtree-splits/blt-project/composer.json.  |
| NodeCheck:checkNodeVersionFileExists         | .nvmrc file exists                                           |
+----------------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
```

**Note, I am aware of the ongoing error with the BLT output on the bottom regarding issue https://github.com/acquia/blt/issues/4002**

**System information**
* Operating system type: DrupalVM hosted on OSX
* Operating system version: DrupalVM : Ubuntu 16.* (64bit) / OSX Catalina
* BLT version: 11.4.0
