### ISSUE TITLE
blt setup is not working as expected

### ISSUE THREAD

**Issue by chuneshlella** [acquia/blt#4228]
When i ran blt setup on the Drupal VM, 

I am getting below errors.

[error]  Invalid drush alias '@default.local'. 
[error]  Invalid drush alias '@default.local'. 
[error]  Command `drupal:install ` exited with code 1.

System Information:
blt: 9.2.8
mac OS: catalina
vagrant: 2.2.8

Any Help will be much appreciated

**Comment by mikemadison13** [comment]
if you are inside the vm, the default local alias should be "self" not @default.local. The VM can't SSH into itself!

**Comment by chuneshlella** [comment]
I came out of VM and ran the blt setup again. I am getting the same error. 

[error]  Invalid drush alias '@default.local'. 
[error]  Invalid drush alias '@default.local'. 
[error]  Command `drupal:install ` exited with code 1.

**Comment by mikemadison13** [comment]
can you share the aliases as defined in your blt.yml file? they should look something like this:

```
drush:
  aliases:
    remote: your.alias
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
```
