### ISSUE TITLE
Where should we declare pre-validate commands in blt.yml?

### ISSUE THREAD

**Issue by loopy3025** [acquia/blt#4318]
**I want to...**
...run a command pre-validate.

**It's not working because...**
...the documentation is unclear as to where this command should go.

https://docs.acquia.com/blt/extending-blt/
https://github.com/consolidation/annotated-command#hooks

**Problem/error**

There is no BLT error. I need to alter a Behat test that's coming from an installation profile after the profile has been installed, but before the Behat test is run. 

I have tried all of the following in the blt.yml for our project:

```
pre-validate:
  dir: ${repo.root}
  command: echo 'Remove default landing page behat test...' && rm docroot/profiles/contrib/??????/tests/behat/features/landing_page.feature && mv docroot/themes/custom/subtheme/behat/features/landing_page.feature docroot/profiles/contrib/??????/tests/behat/features/

validate: 
  pre-validate:
    dir: ${repo.root}
    command: echo 'Remove default landing page behat test...' && rm docroot/profiles/contrib/??????/tests/behat/features/landing_page.feature && mv docroot/themes/custom/subtheme/behat/features/landing_page.feature docroot/profiles/contrib/??????/tests/behat/features/

post-deploy-build:
  dir: ${repo.root}
  command: echo 'Remove default landing page behat test...' && rm docroot/profiles/contrib/??????/tests/behat/features/landing_page.feature && mv docroot/themes/custom/subtheme/behat/features/landing_page.feature docroot/profiles/contrib/??????/tests/behat/features/

deploy:
  post-deploy-build:
    dir: ${repo.root}
    command: echo 'Remove default landing page behat test...' && rm docroot/profiles/contrib/??????/tests/behat/features/landing_page.feature && mv docroot/themes/custom/subtheme/behat/features/landing_page.feature docroot/profiles/contrib/??????/tests/behat/features/

command-hooks:
  post-deploy-build:
    dir: ${repo.root}
    command: echo 'Remove default landing page behat test...' && rm docroot/profiles/contrib/??????/tests/behat/features/landing_page.feature && mv docroot/themes/custom/subtheme/behat/features/landing_page.feature docroot/profiles/contrib/??????/tests/behat/features/
  pre-validate:
    dir: ${repo.root}
    command: echo 'Remove default landing page behat test...' && rm docroot/profiles/contrib/??????/tests/behat/features/landing_page.feature && mv docroot/themes/custom/subtheme/behat/features/landing_page.feature docroot/profiles/contrib/??????/tests/behat/features/

target-hooks:
  post-deploy-build:
    dir: ${repo.root}
    command: echo 'Remove default landing page behat test...' && rm docroot/profiles/contrib/??????/tests/behat/features/landing_page.feature && mv docroot/themes/custom/subtheme/behat/features/landing_page.feature docroot/profiles/contrib/??????/tests/behat/features/
  pre-validate:
    dir: ${repo.root}
    command: echo 'Remove default landing page behat test...' && rm docroot/profiles/contrib/??????/tests/behat/features/landing_page.feature && mv docroot/themes/custom/subtheme/behat/features/landing_page.feature docroot/profiles/contrib/??????/tests/behat/features/

```
I have even tried totally hijacking the entire validate command, but all it does is run the normal command.
```
validate:
  command: echo 'Remove default landing page behat test...' && rm ${repo.root}/docroot/profiles/contrib/??????/tests/behat/features/landing_page.feature && mv ${repo.root}/docroot/themes/custom/subtheme/behat/features/landing_page.feature ${repo.root}/docroot/profiles/contrib/??????/tests/behat/features/ && echo 'Executing validate command...' && source ${BLT_DIR}/scripts/pipelines/validate
```

I am quite at a loss as none of these seem to be firing according to my logs in pipelines.

**BLT doctor output**
```
 fin blt doctor
+---------------------------+------------------------------------------------+
| Property                  | Value                                          |
+---------------------------+------------------------------------------------+
| %paths.%root              | /var/www/docroot                               |
| %paths.%site              | sites/default                                  |
| %paths.%modules           | sites/all/modules                              |
| %paths.%themes            | sites/all/themes                               |
| %paths.%config-core       | profiles/contrib/??????/config/install          |
| %paths.%config-sync       | /var/www/config/default                        |
| %paths.%config-custom     | ../config/custom                               |
| %paths.%files             | sites/default/files                            |
| %paths.%temp              | /tmp                                           |
| %paths.%private           | /var/www/files-private                         |
| admin-theme               | ??????commander                                 |
| alias-searchpaths.0       | /var/www/drush/sites                           |
| blt-version               | 11.6.0                                         |
| bootstrap                 | Successful                                     |
| composer-version          | Composer version 1.9.0 2019-08-02 20:55:32     |
| config-sync               | /var/www/config/default                        |
| db-driver                 | mysql                                          |
| db-hostname               | db                                             |
| db-name                   | default                                        |
| db-password               | user                                           |
| db-port                   | 3306                                           |
| db-status                 | Connected                                      |
| db-username               | user                                           |
| drupal-settings-file      | sites/default/settings.php                     |
| drupal-version            | 8.9.11                                         |
| drush-alias-files.0       | /var/www/drush/sites/???????.site.yml           |
| drush-cache-directory     | /home/docker/.drush/cache                      |
| drush-conf.0              | /var/www/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/drush/drush.yml                       |
| drush-conf.2              | /var/www/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/vendor/drush/drush/drush              |
| drush-temp                | /tmp                                           |
| drush-version             | 10.3.6                                         |
| files                     | sites/default/files                            |
| install-profile           | ??????                                          |
| modules                   | sites/all/modules                              |
| php-bin                   | /usr/local/bin/php                             |
| php-conf.1                | false                                          |
| php-os                    | Linux                                          |
| private                   | /var/www/files-private                         |
| root                      | /var/www/docroot                               |
| site                      | sites/default                                  |
| stacks.drupal-vm.inited   | false                                          |
| stacks.dev-desktop.inited | false                                          |
| temp                      | /tmp                                           |
| theme                     | subtheme                                       |
| themes                    | sites/all/themes                               |
| uri                       | http://???????.docksal                            |
+---------------------------+------------------------------------------------+
+---------------------------------------+-------------------------------------------------------------+
| Check                                 | Problem                                                     |
+---------------------------------------+-------------------------------------------------------------+
| ComposerCheck:composer.autoload.psr-4 | The Composer configuration for autoload.psr-4 differs from  |
|                                       | BLT's default, recommended values.                          |
|                                       |   Change your configuration to match BLT's defaults in      |
|                                       |                                                             |
|                                       | vendor/acquia/blt/subtree-splits/blt-project/composer.json. |
| ComposerCheck:composer.scripts.nuke   | The Composer configuration for scripts.nuke differs from    |
|                                       | BLT's default, recommended values.                          |
|                                       |   Change your configuration to match BLT's defaults in      |
|                                       |                                                             |
|                                       | vendor/acquia/blt/subtree-splits/blt-project/composer.json. |
| NodeCheck:checkNodeVersionFileExists  | .nvmrc file exists                                          |
| WebUriCheck:checkUriResponse          | Did not get a response from http://???????.docksal             |
|                                       | Is your *AMP stack running?                                 |
|                                       | Is your /etc/hosts file correctly configured?               |
|                                       | Is your web server configured to serve this URI from        |
|                                       | /var/www/docroot?                                           |
|                                       | Is options.uri set correctly in                             |
|                                       | /var/www/docroot/sites/default/local.drush.yml?             |
+---------------------------------------+-------------------------------------------------------------+
```

**System information**
* Operating system type: Mac OS
* Operating system version: 10.15.6
* BLT version: 11.6.0
