### ISSUE TITLE
Some command-hooks defined in build.yml are never called 

### ISSUE THREAD

**Issue by clfer** [acquia/blt#4409]
**Describe the bug**
Some command-hooks defined in `build.yml` are never called.
In the listed example I identified the following that are never called:
`pre-commit`
`post-deploy`

Following #4320, the [doc](https://docs.acquia.com/blt/extending-blt/#acquia-blt-native-command-hooks) is up to date with valid command-hooks but not the `build.yml`

**To Reproduce**
1. Set a command-hooks in blt.yml
```
command-hooks
  pre-commit:
    dir: ${docroot}
    command: blt validate:phpcs:staged
```
2. Run the pre-commit command
`blt internal:git-hook:execute:pre-commit "${LIST}"`

**Expected behavior**
The `blt validate:phpcs:staged` command is executed after the pre-commit.

**Current behavior**
The command is not executed
