### ISSUE TITLE
Tag-based Travis deploys don't work

### ISSUE THREAD

**Issue by bmartinez287** [acquia/blt#4425]
Related to https://github.com/acquia/blt/issues/968

It seems like travis rollout an update last week that is breaking tag-based deployments.

Our travis file runs well until it reaches the tags: true which never happens.
```
deploy:
  - provider: script
    script: "${BLT_TRAVIS_DIR}/scripts/deploy_branch"
    cleanup: false
    edge: true
    on:
      branch: develop
      php: 7.4
  - provider: script
    script: "${BLT_TRAVIS_DIR}/scripts/deploy_branch"
    cleanup: false
    edge: true
    on:
      branch: master
      php: 7.4
  - provider: script
    script: "${BLT_TRAVIS_DIR}/scripts/deploy_tag"
    cleanup: false
    edge: true
    on:
      tags: true
      php: 7.4



```
