### ISSUE TITLE
DX-5139: Error when trying to make a commit due to error in git hooks

### ISSUE THREAD

**Issue by shelane** [acquia/blt#4558]
**Describe the bug**
After upgrading to 13.5.0 from 13.4.0, I get an error every time I go to make a commit.

My configuration in my `blt.yml` file for git hooks are:
```
git:
  default_branch: master
  remotes:
    - 'redacted'
  commit-msg:
    pattern: '/(^DRUPAL-[0-9]+)|(Merge branch)/'
  hooks:
    pre-push: false
```

**To Reproduce**
1. I don't know if a custom commit-msg pattern is required. I've only tested my site that has one. So, set in `blt.yml` file.
2. Make a change to a file.
3. Write a commit statement that should pass with the pattern.

**Expected behavior**
I expect to be able to commit my change without error.

**Detailed error output**
```
Executing .git/hooks/pre-commit...
Untracked files are present, this may impact the validity of pre-commit checks.
> validate:twig:lint:files
Linting twig files...
All Twig files contain valid syntax.
> validate:yaml:lint:files
Linting YAML files...
Your local code has passed git pre-commit validation.
Executing .git/hooks/commit-msg...

                                                 
  Command ".git/COMMIT_EDITMSG" is not defined.
```

**System information**
* Operating system type: macos
* Operating system version:  11.6.7
* BLT version: 13.5.0

**Additional context**
