### ISSUE TITLE
drush.yml config path relative to site and project root directory

### ISSUE THREAD

**Issue by guedressel** [acquia/blt#4613]
`drush`s config path loading "relative to the current working directory" is not robust when a Drupal site is run different environments (with different directory structures and user preferences). Using absolute paths - on the other hand - is also not practical when working on different environments.

Therfore a "project root"- and "site"-shortcut would be handy to describe relative paths rooted from the Drupal site directory.

```
drush:
  paths:
    config:
      - ${site}/site.drush.yml
      - ${root}/drush/local.drush.yml
      - ${env.HOME}/.drush/config/drush.yml

```
