### ISSUE TITLE
Default DrupalVM to PHP 5.6

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#501]
Currently the blt vm target installs a vanilla drupalvm which includes ubuntu 16 and PHP7.  For parity with acquia cloud it should instead install ubuntu 1404 and PHP 5.6.

cc: @geerlingguy

**Comment by geerlingguy** [comment]
The changes would need to be, basically:

```yaml
# Use Ubuntu 14.04 LTS so PHP 5.6 can be installed.
vagrant_box: geerlingguy/ubuntu1404

# Use PHP 5.6 and change package names to work with 5.6.
php_version: "5.6"
php_packages:
  - php5
  - php5-apcu
  - php5-mcrypt
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-fpm
  - php5-gd
  - php5-sqlite
  - php-pear
  - libpcre3-dev
php_conf_paths:
  - /etc/php5/fpm
  - /etc/php5/apache2
  - /etc/php5/cli
php_extension_conf_paths:
  - /etc/php5/fpm/conf.d
  - /etc/php5/apache2/conf.d
  - /etc/php5/cli/conf.d
php_fpm_daemon: php5-fpm
php_fpm_conf_path: "/etc/php5/fpm"
php_fpm_pool_conf_path: "/etc/php5/fpm/pool.d/www.conf"
php_mysql_package: php5-mysql
php_redis_package: php5-redis
php_memcached_package: php5-memcached

xhprof_download_url: https://github.com/phacility/xhprof/archive/master.tar.gz
xhprof_download_folder_name: xhprof-master
```
