### ISSUE TITLE
Drupal VM integration broken in latest stable release of DrupalVM

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#568]
After initializing a fresh blt project: 
```
composer create-project acquia/blt-project mtacc --no-interaction
```

When I ssh into the VM I get:

```
vagrant@mysite:/var/www/mysite$ php --version
PHP 7.0.12-1+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12-1+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
```

Here is the config.yml

```
# Update the hostname to the local development environment hostname
vagrant_hostname: mysite.localhost
vagrant_machine_name: mysite

# Use Ubuntu 14.04 LTS so PHP 5.6 can be installed.
vagrant_box: geerlingguy/ubuntu1404

# Set drupal_site_name to the project's human-readable name.
drupal_site_name: "mysite"

# Provide the path to the project root to Vagrant.
vagrant_synced_folders:
  # Set the local_path for the first synced folder to `.`.
  - local_path: .
    # Set the destination to the Acquia Cloud subscription machine name.
    destination: /var/www/mysite
    type: nfs

build_composer_project: false
# Toggling this to `true` would invoke `composer install` with the
# projects own `composer.json` successfully.
build_composer: false
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/mysite"
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"

drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_database: drupal

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
install_site: false

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_drush_aliases: false

# This is required for front-end building tools.
nodejs_version: "0.12"
nodejs_npm_global_packages:
  - name: bower
  - name: gulp-cli
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"
installed_extras:
  - nodejs

# Use PHP 5.6 and change package names to work with 5.6.
php_version: "5.6"
php_packages:
  - php5
  - php5-apcu
  - php5-mcrypt
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-fpm
  - php5-gd
  - php5-sqlite
  - php-pear
  - libpcre3-dev
php_conf_paths:
  - /etc/php5/fpm
  - /etc/php5/apache2
  - /etc/php5/cli
php_extension_conf_paths:
  - /etc/php5/fpm/conf.d
  - /etc/php5/apache2/conf.d
  - /etc/php5/cli/conf.d
php_fpm_daemon: php5-fpm
php_fpm_conf_path: "/etc/php5/fpm"
php_fpm_pool_conf_path: "/etc/php5/fpm/pool.d/www.conf"
php_mysql_package: php5-mysql
php_redis_package: php5-redis
php_memcached_package: php5-memcached

# Use PHP 5.6-compatible version of XHProf.
xhprof_download_url: https://github.com/phacility/xhprof/archive/master.tar.gz
xhprof_download_folder_name: xhprof-master

extra_packages:
  # This is required for PhantomJS Installer.
  - php-bz2
  - subversion
  - php-bcmath

post_provision_scripts:
  - "../../../acquia/blt/scripts/drupal-vm/post-provision.sh"

composer_global_packages: []

ssh_home: "/var/www/mysite"

```

Noteworthy I did have to manually add the following before I could do a vagrant up to prevent global composer errors.
```
composer_global_packages: []
```
