### ISSUE TITLE
Git-hooks configuration

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#628]
Would there be any consideration given to the ability to enable/disable the git-hooks through a setting, maybe in `project.yml` or a custom phing build file?

Ideally, I would like the ability to have more flexibility around the git-hooks. I could see wanting to disable only the `commit-msg` git hook, or maybe providing my own `commit-msg` file altogether.

The setup today makes it a little difficult and it is more "all or nothing". Maybe instead of just sym-linking `.git/hooks` -> `vendor/acquia/blt/scripts/git-hooks`, we could symlink to the individual files, and you could override each file location with a project specific file...? 

build.yml could have:
```yml
git-hooks:
  - commit-msg: ${blt.root}/scripts/git-hooks/
  - pre-commit: ${blt.root}/scripts/git-hooks/
```

...then, in my project, I can override those with:
```yml
git-hooks:
  - commit-msg: false
  - pre-commit: ${repo.root}/blt/scripts/git-hooks/
```

Thoughts?

Again, happy to give this a shot and produce a PR, just want to get some feedback first.
