### ISSUE TITLE
More granular control of modules per environment

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#668]
Right now, you can select which modules to enable/disable for local, remote ("deploy"), and ci environments. Many (most?) projects need more granular control than this.

For instance, it's pretty typical to enable development modules in a remote dev environment. You might also want a smaller subset of development modules for the stage environment (for instance, to create dummy users or content for UAT). You wouldn't want either of these in prod.

I'm trying to think of the best way to support these scenarios, since adding even more elements to the module array in `project.yml` seems pretty clunky.

**Comment by grasmash** [comment]
These are really mapping to targets... local:update, ci:update, deploy:update. Where you call these targets is up to you. So, you can call `local:update` on your cloud dev environment in a cloud hook if you'd like. Is that sufficient?

**Comment by danepowell** [comment]
Yeah, I think this needs to be decoupled from specific `update` commands. Those commands make assumptions about the environments they are run in (`deploy:update` sets the VCS config directory, while `local:update` does not), and for this reason we also hardcode `deploy:update` in the cloud hook.

So just introducing a new command wouldn't be enough... I think the cloud hook needs to pass the name of its environment (dev/stage/prod) as an argument to `deploy:update`, and `deploy:update` needs to be able to toggle the appropriate modules based on the environment.

**Comment by grasmash** [comment]
Hm. We could provide dev, ci, and prod by default:
```
# An array of modules to be enabled or uninstalled automatically in local, ci, and deploy contexts.
modules:
  ci:
    enable: []
    uninstall:
      - acquia_connector
      - shield
  dev:
    enable:
      - dblog
      - devel
      - field_ui
      - seckit
      - views_ui
    uninstall:
      - acsf
      - acquia_connector
      - shield
  prod:
    enable:
      - acquia_connector
      - shield
    uninstall:
      - devel
      - field_ui
      - views_ui
```

Then create a `setup:toggle-modules` target that accepts a `env` parameter. `local:update` can pass `dev` as the env value by default.  

We can call cloud hooks with `blt deploy:update -Denv=$ENV` then. The thing I don't like about that is that you can't share modules array across multiple environments easily.

An advantage is that you can then also create your own arbitrary `test` or `qa` envs and toggle those in your own commands with `blt setup:toggle-modules -Denv=qa`.
