### ISSUE TITLE
Support multiple hostnames/vhosts for a single site

### ISSUE THREAD

**Issue by ba66e77** [acquia/blt#798]
### User Story
As a developer working on a site which uses a separate edit domain to partition content creator access from public access, I want BLT to support creating multiple hostnames for a single site so that the 'blt vm' will properly set the drupal-vm config.yml options.

### Elaboration
In Drupal VM we can add multiple hostnames/vhosts for a single site (i.e., not a multisite setup) by adding entries in the apache_vhosts section of config.yml.  When running `blt vm` the drupalvm config.yml is setup automatically but blt does not currently allow multiple entries in the project:local:hostname section of project.yml so the config.yml must be hand edited to add additional apache_vhosts.

**Comment by captaindav** [comment]
I believe I have the same need, I have thee sites that have three databases and one codebase, I would rather not use multi-site as it has been deprecated, and I found it hard to use in the past.  Does any know of a work-around for now, where I would have one BLT project for the three sites, but not use multisite?

**Comment by ba66e77** [comment]
@captaindav I see that [deprecation of multisite was brought up as an issue](https://www.drupal.org/node/2306013), but Closed as a Works as Designed.  It doesn't seem like it's going away to me.

That said, the work around I found to my need was to hand hack the config.yml to add multiple domains to the generated apache vhosts file.

**Comment by grasmash** [comment]
Addressed by: #1916.

**Comment by marcosimbuerger** [comment]
> That said, the work around I found to my need was to hand hack the config.yml to add multiple domains to the generated apache vhosts file.

I did the same, but this work around overrides all vhost configurations from BLT/Drupal VM (dashboard, adminer, ...). Is it possible to extend the default vhost config from BLT?

I have added this code to config.yml:
```
apache_vhosts:
  - servername: "frontend.{{ drupal_domain }}"
    serveralias: "www.frontend.{{ drupal_domain }}"
    documentroot: "{{ ssh_home }}/frontend"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
```
