### ISSUE TITLE
Add Pipelines to DrupalVM

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#870]

**Comment by geerlingguy** [comment]
Something like:

```yaml
- name: Install Pipelines.
  get_url:
    url: url-to-pipelines-download-here
    dest: /usr/local/pipelines
    mode: 0755
```

Using a post-provision task file: http://docs.drupalvm.com/en/latest/extras/scripts/#ansible-task-files
