### ISSUE TITLE
BLT Upgrades keep adding back modules to project.yml

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#888]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.2
* BLT version: 8.6.5

When I run this command:
```
composer update # as part of BLT upgrade
```

My `blt/project.yml` `modules` listing gets messed up. I have manually set the `ci` environment to not enable or disable any modules (see below), but every time I upgrade BLT, it ends up getting some defaults repopulated.

```yaml
modules:
  local:
    enable: [dblog, devel, features_ui, field_ui, seckit, update, views_ui]
    uninstall: [shield]
  ci:
    enable: {  }
    uninstall: {  }
  dev:
    enable: [acquia_connector, shield]
    uninstall: {  }
  test:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
  prod:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
```
