### ISSUE TITLE
Tag-based Travis deploys don't work

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#968]
#908 added Travis-based deployments for tags. However, these deploys always fail because a deploy.branch is required in several places in deploy.xml: https://github.com/acquia/blt/blob/8.x/phing/tasks/deploy.xml#L60

**Comment by grasmash** [comment]
Hm. I think that we should perhaps expect that both a branch and a tag are created when a tag is created. In that case, this is the correct behavior--branch should always be specified. We just need to update the call to the deploy target in the templated .travis.yml.

**Comment by arknoll** [comment]
My travis.yml looks like this:

```
 - provider: script
     script: blt deploy -Ddeploy.commitMsg="Automated commit by Travis CI for Build ${TRAVIS_TAG}" -Ddeploy.branch="master-build" -Ddeploy.tag="${TRAVIS_TAG}" -Ddeploy.tag.create="y"
     skip_cleanup: true
     on:
       tags: true
       php: 5.6
```

But note, this only works if you are applying your tag to the master branch.
